
% precondition: input_button_name is a string array of size 19
%              multi_trip_prices is an int array of size 8
%              single_trip_price is an int array of size 8
%              daytrip_price is an int array of size 3

function output = cigarette( function_name , input_button_name , input_prices )

    mouse_pointer = watchon();
    
    format short g;
    
    %panel construction variables
    SCREEN_DETAILS = get(0,'ScreenSize');
    fig_x = 1000;
    fig_y = 690;
    
    CIGARETTE_FIGURE = figure( 'Name' , 'Cigarettes' , ...
                               'Units', 'pixels'     , ...
                               'resize', 'off'       , ...
                               'NumberTitle' , 'off' , ...
                               'Visible' , 'on'      , ...
                               'position', [ 10 , abs( SCREEN_DETAILS(4) - fig_y - 45 ) ,  fig_x , fig_y ] ...
                             );
                       
    colordef( CIGARETTE_FIGURE  , 'black' );
    
    
    white = [ 1 1 1 ];
    black = [ 0 0 0 ];
    colour_display = [ 0.9 0.9 0.9 ];
    
    colour_1  = [ 0.4 0.4 0.4 ];
    colour_2  = [ 0.60 0.60 0.60 ];
    colour_3  = [ 0.85 0.85 0.85 ];
    colour_4  = [ 0.90 .9 .4 ];
    colour_5  = [ 0.70 1 0.65 ];
    colour_6  = [ 0.8 0.20 0.18 ];
    colour_7  = [ .60 0.17 0.1 ];
    colour_8  = [ .33 0.17 0.2 ];
    colour_9  = [ 0.19 0.24 1 ];
    colour_10  = [ 0.1 0.54 0.73 ];
    colour_11  = [ 0.4 0.6 0.8 ];
    colour_12  = [ 1 1 .95 ];
    colour_13  = [ .5 0.2 0.01 ];
    colour_14  = [ 0.89 0.7 0.8 ];
    colour_15  = [ 0.63 0.51 0.1 ];
    colour_16  = [ 0.1 0.45 0.19 ];
    colour_17  = [ 0.1 0.7 0.3 ];
    colour_18  = [ 0.34 0.84 0.1 ];
    colour_19  = [ 0.20 0.40 0.80 ];
    colour_20  = [ 0.8 0.27 0 ];
    colour_21  = [ .75 0.01 0.01 ];
    colour_22  = [ 0.5 0.5 0.8 ];
    colour_23  = [ 0.8 0.4 0.27 ];
    colour_24  = [ 0.74 0.84 0.1 ];
    
    % panel
    %----------------------------  begin  ---------------------------------
    %----------------------------------------------------------------------
    LEFT_PANEL = uipanel( 'Parent' , CIGARETTE_FIGURE         , ...
                          'FontName' , 'Arial'                , ...
                          'FontUnits' , 'points'              , ...
                          'FontWeight' , 'bold'               , ...
                          'FontSize' , 15                     , ...
                          'Units' , 'pixels'                  , ...
                          'Visible' , 'on'                    , ...
                          'BackgroundColor' , white           , ...
                          'Position' , [ 20 , 30 , 270 , 630 ]  ...
                        );  
                       
                           
     MIDDLE_PANEL = uipanel( 'Parent' , CIGARETTE_FIGURE           , ...
                             'FontName' , 'Arial'                  , ...
                             'FontUnits' , 'points'                , ...
                             'FontWeight' , 'bold'                 , ...
                             'FontSize' , 15                       , ...
                             'Units' , 'pixels'                    , ...
                             'Visible' , 'on'                      , ...
                             'BackgroundColor' , white             , ...
                             'Position' , [ 300 , 30 , 190 , 630 ]   ...
                           );  
                       
                           
     RIGHT_PANEL = uipanel( 'Parent' , CIGARETTE_FIGURE            , ...
                            'FontName' , 'Arial'                   , ...
                            'FontUnits' , 'points'                 , ...
                            'FontWeight' , 'bold'                  , ...
                            'FontSize' , 15                        , ...
                            'Units' , 'pixels'                     , ...
                            'Visible' , 'on'                       , ...
                            'BackgroundColor' , white              , ...
                            'Position' , [ 500 , 30  , 350 , 630 ]   ...
                          );
                       
                                                                
                            
    
    % panel
    %----------------------------  end  ---------------------------------
    %----------------------------------------------------------------------                      
                           
    
    
    
    
    
    
    % buttons
    % ============================ begin ==================================
    % =====================================================================
 
      
           price = num2str( input_prices(1,1) , '%2.2f');
           price = [ '$' , price ];  
           callbr = callname( function_name , char(input_button_name(1,1)) ); 
           button_1 = uicontrol( 'String' , price                    , ...
                                 'Parent' , LEFT_PANEL               , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_1        , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 475 , 135 , 103 ]  ...                                        
                               );
           
           
           price = num2str( input_prices(1,2) , '%2.2f');
           price = [ '$' , price ];     
           callbr = callname( function_name , char(input_button_name(1,2)) );                                    
           button_2 = uicontrol( 'String' , price                    , ...
                                 'Parent' , LEFT_PANEL               , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_2        , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 317 , 135 , 103 ]  ...                                        
                               );
                     
                   
           price = num2str( input_prices(1,3) , '%2.2f');
           price = [ '$' , price ];                                     
           callbr = callname( function_name , char(input_button_name(1,3)) );                                    
           button_3 = uicontrol( 'String' , price                     , ...
                                 'Parent' , LEFT_PANEL                , ...
                                 'Style' , 'pushbutton'               , ...
                                 'Callback' , callbr                  , ...
                                 'HorizontalAlignment' , 'center'     , ...
                                 'Units' , 'pixels'                   , ...
                                 'Visible' , 'on'                     , ...
                                 'BackgroundColor' , colour_3         , ... 
                                 'ForegroundColor' , black            , ...
                                 'FontUnits' , 'pixels'               , ...
                                 'FontSize' , 16                      , ...
                                 'Position' , [ 1 , 159 , 135 , 103 ]  ...                                        
                               );
                             
                       
           price = num2str( input_prices(1,4) , '%2.2f');
           price = [ '$' , price ];                                  
           callbr = callname( function_name , char(input_button_name(1,4)) );                                    
           button_4 = uicontrol( 'String' , price                      , ...
                                 'Parent' , LEFT_PANEL                 , ...
                                 'Style' , 'pushbutton'                , ...
                                 'Callback' , callbr                   , ...
                                 'HorizontalAlignment' , 'center'      , ...
                                 'Units' , 'pixels'                    , ...
                                 'Visible' , 'on'                      , ...
                                 'BackgroundColor' , colour_4          , ... 
                                 'ForegroundColor' , black             , ...
                                 'FontUnits' , 'pixels'                , ...
                                 'FontSize' , 16                       , ...
                                 'Position' , [ 136 , 317 , 135 , 261 ]  ...                                        
                               );
                             
                               
           price = num2str( input_prices(1,5) , '%2.2f');
           price = [ '$' , price ];                                    
           callbr = callname( function_name , char(input_button_name(1,5)) );                                    
           button_5 = uicontrol( 'String' , price                      , ...
                                 'Parent' , LEFT_PANEL                 , ...
                                 'Style' , 'pushbutton'                , ...
                                 'Callback' , callbr                   , ...
                                 'HorizontalAlignment' , 'center'      , ...
                                 'Units' , 'pixels'                    , ...
                                 'Visible' , 'on'                      , ...
                                 'BackgroundColor' , colour_5          , ... 
                                 'ForegroundColor' , black             , ...
                                 'FontUnits' , 'pixels'                , ...
                                 'FontSize' , 16                       , ...
                                 'Position' , [ 136 , 159 , 135 , 103 ]  ...                                        
                               );
                                    
           price = num2str( input_prices(1,6) , '%2.2f');
           price = [ '$' , price ];                                    
           callbr = callname( function_name , char(input_button_name(1,6)) );                                    
           button_6 = uicontrol( 'String' , price                 , ...
                                 'Parent' , LEFT_PANEL            , ...
                                 'Style' , 'pushbutton'           , ...
                                 'Callback' , callbr              , ...
                                 'HorizontalAlignment' , 'center' , ...
                                 'Units' , 'pixels'               , ...
                                 'Visible' , 'on'                 , ...
                                 'BackgroundColor' , colour_6     , ... 
                                 'ForegroundColor' , black        , ...
                                 'FontUnits' , 'pixels'           , ...
                                 'FontSize' , 16                  , ...
                                 'Position' , [ 1 , 1 , 90 , 88 ]   ...                                        
                               );
                                
           price = num2str( input_prices(1,7) , '%2.2f');
           price = [ '$' , price ];                               
           callbr = callname( function_name , char(input_button_name(1,7)) );                                    
           button_7 = uicontrol( 'String' , price                  , ...
                                 'Parent' , LEFT_PANEL             , ...
                                 'Style' , 'pushbutton'            , ...
                                 'Callback' , callbr               , ...
                                 'HorizontalAlignment' , 'center'  , ...
                                 'Units' , 'pixels'                , ...
                                 'Visible' , 'on'                  , ...
                                 'BackgroundColor' , colour_7      , ... 
                                 'ForegroundColor' , black         , ...
                                 'FontUnits' , 'pixels'            , ...
                                 'FontSize' , 16                   , ...
                                 'Position' , [ 91 , 1 , 90 , 88 ]   ...                                        
                               );
                                
                               
           price = num2str( input_prices(1,8) , '%2.2f');
           price = [ '$' , price ];                                 
           callbr = callname( function_name , char(input_button_name(1,8)) );                                    
           button_8 = uicontrol( 'String' , price                   , ...
                                 'Parent' , LEFT_PANEL              , ...
                                 'Style' , 'pushbutton'             , ...
                                 'Callback' , callbr                , ...
                                 'HorizontalAlignment' , 'center'   , ...
                                 'Units' , 'pixels'                 , ...
                                 'Visible' , 'on'                   , ...
                                 'BackgroundColor' , colour_8       , ... 
                                 'ForegroundColor' , black          , ...
                                 'FontUnits' , 'pixels'             , ...
                                 'FontSize' , 16                    , ...
                                 'Position' , [ 182 , 1 , 90 , 88 ]   ...                                        
                               );
                             
                               
           price = num2str( input_prices(1,9) , '%2.2f');
           price = [ '$' , price ];                                 
           callbr = callname( function_name , char(input_button_name(1,9)) );                                    
           button_9 = uicontrol( 'String' , price                    , ...
                                 'Parent' , MIDDLE_PANEL             , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_9        , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 475 , 90 , 103 ]   ...                                        
                               );
                           
                               
           price = num2str( input_prices(1,10) , '%2.2f');
           price = [ '$' , price ];                                  
           callbr = callname( function_name , char(input_button_name(1,10)) );                                    
           button_10 = uicontrol( 'String' , price                   , ...
                                 'Parent' , MIDDLE_PANEL             , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_10       , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 317 , 90 , 103 ]   ...                                        
                               );
                 
                               
           price = num2str( input_prices(1,11) , '%2.2f');
           price = [ '$' , price ];                                  
           callbr = callname( function_name , char(input_button_name(1,11)) );                                    
           button_11 = uicontrol( 'String' , price                   , ...
                                 'Parent' , MIDDLE_PANEL             , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_11       , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 159 , 90 , 103 ]   ...                                        
                               );
                     
                               
           price = num2str( input_prices(1,12) , '%2.2f');
           price = [ '$' , price ];                                 
           callbr = callname( function_name , char(input_button_name(1,12)) );                                    
           button_12 = uicontrol( 'String' , price                     , ...
                                 'Parent' , MIDDLE_PANEL               , ...
                                 'Style' , 'pushbutton'                , ...
                                 'Callback' , callbr                   , ...
                                 'HorizontalAlignment' , 'center'      , ...
                                 'Units' , 'pixels'                    , ...
                                 'Visible' , 'on'                      , ...
                                 'BackgroundColor' , colour_12         , ... 
                                 'ForegroundColor' , black             , ...
                                 'FontUnits' , 'pixels'                , ...
                                 'FontSize' , 16                       , ...
                                 'Position' , [ 91 , 475 , 100 , 103 ]   ...                                        
                               );
                
                               
           price = num2str( input_prices(1,13) , '%2.2f');
           price = [ '$' , price ];                                    
           callbr = callname( function_name , char(input_button_name(1,13)) );                                    
           button_13 = uicontrol( 'String' , price                      , ...
                                  'Parent' , MIDDLE_PANEL               , ...
                                  'Style' , 'pushbutton'                , ...
                                  'Callback' , callbr                   , ...
                                  'HorizontalAlignment' , 'center'      , ...
                                  'Units' , 'pixels'                    , ...
                                  'Visible' , 'on'                      , ...
                                  'BackgroundColor' , colour_13         , ... 
                                  'ForegroundColor' , black             , ...
                                  'FontUnits' , 'pixels'                , ...
                                  'FontSize' , 16                       , ...
                                  'Position' , [ 91 , 317 , 100 , 103 ]   ...                                        
                                );
          
                                
           price = num2str( input_prices(1,14) , '%2.2f');
           price = [ '$' , price ];                              
           callbr = callname( function_name , char(input_button_name(1,14)) );                                    
           button_14 = uicontrol( 'String' , price                      , ...
                                  'Parent' , MIDDLE_PANEL               , ...
                                  'Style' , 'pushbutton'                , ...
                                  'Callback' , callbr                   , ...
                                  'HorizontalAlignment' , 'center'      , ...
                                  'Units' , 'pixels'                    , ...
                                  'Visible' , 'on'                      , ...
                                  'BackgroundColor' , colour_14         , ... 
                                  'ForegroundColor' , black             , ...
                                  'FontUnits' , 'pixels'                , ...
                                  'FontSize' , 16                       , ...
                                  'Position' , [ 90 , 159 , 100 , 103 ]   ...                                        
                                );
                
                                
           price = num2str( input_prices(1,15) , '%2.2f');
           price = [ '$' , price ];                                  
           callbr = callname( function_name , char(input_button_name(1,15)) );                                    
           button_15 = uicontrol( 'String' , price                  , ...
                                  'Parent' , MIDDLE_PANEL           , ...
                                  'Style' , 'pushbutton'            , ...
                                  'Callback' , callbr               , ...
                                  'HorizontalAlignment' , 'center'  , ...
                                  'Units' , 'pixels'                , ...
                                  'Visible' , 'on'                  , ...
                                  'BackgroundColor' , colour_15     , ... 
                                  'ForegroundColor' , black         , ...
                                  'FontUnits' , 'pixels'            , ...
                                  'FontSize' , 16                   , ...
                                  'Position' , [ 1 , 1 , 190 , 88 ]   ...                                        
                                );
                 
                                
           price = num2str( input_prices(1,16) , '%2.2f');
           price = [ '$' , price ];                                  
           callbr = callname( function_name , char(input_button_name(1,16)) );                                    
           button_16 = uicontrol( 'String' , price                    , ...
                                  'Parent' , RIGHT_PANEL              , ...
                                  'Style' , 'pushbutton'              , ...
                                  'Callback' , callbr                 , ...
                                  'HorizontalAlignment' , 'center'    , ...
                                  'Units' , 'pixels'                  , ...
                                  'Visible' , 'on'                    , ...
                                  'BackgroundColor' , colour_16       , ... 
                                  'ForegroundColor' , black           , ...
                                  'FontUnits' , 'pixels'              , ...
                                  'FontSize' , 16                     , ...
                                  'Position' , [ 1 , 475 , 80 , 103 ]   ...                                        
                                );
               
                                
           price = num2str( input_prices(1,17) , '%2.2f');
           price = [ '$' , price ];                                 
           callbr = callname( function_name , char(input_button_name(1,17)) );                                    
           button_17 = uicontrol( 'String' , price                   , ...
                                 'Parent' , RIGHT_PANEL              , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_17       , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 317 , 80 , 103 ]   ...                                        
                               );
                 
                                 
           price = num2str( input_prices(1,18) , '%2.2f');
           price = [ '$' , price ];                                 
           callbr = callname( function_name , char(input_button_name(1,18)) );                                    
           button_18 = uicontrol( 'String' , price                   , ...
                                 'Parent' , RIGHT_PANEL              , ...
                                 'Style' , 'pushbutton'              , ...
                                 'Callback' , callbr                 , ...
                                 'HorizontalAlignment' , 'center'    , ...
                                 'Units' , 'pixels'                  , ...
                                 'Visible' , 'on'                    , ...
                                 'BackgroundColor' , colour_18       , ... 
                                 'ForegroundColor' , black           , ...
                                 'FontUnits' , 'pixels'              , ...
                                 'FontSize' , 16                     , ...
                                 'Position' , [ 1 , 159 , 80 , 103 ]   ...                                        
                               );
              
                               
           price = num2str( input_prices(1,19) , '%2.2f');
           price = [ '$' , price ];                           
           callbr = callname( function_name , char(input_button_name(1,19)) );                                    
           button_19 = uicontrol( 'String' , price                     , ...
                                  'Parent' , RIGHT_PANEL               , ...
                                  'Style' , 'pushbutton'               , ...
                                  'Callback' , callbr                  , ...
                                  'HorizontalAlignment' , 'center'     , ...
                                  'Units' , 'pixels'                   , ...
                                  'Visible' , 'on'                     , ...
                                  'BackgroundColor' , colour_19        , ... 
                                  'ForegroundColor' , black            , ...
                                  'FontUnits' , 'pixels'               , ...
                                  'FontSize' , 16                      , ...
                                  'Position' , [ 81 , 475 , 90 , 103 ]   ...                                        
                                );
                                 
                               
           price = num2str( input_prices(1,20) , '%2.2f');
           price = [ '$' , price ];                                    
           callbr = callname( function_name , char(input_button_name(1,20)) );                                    
           button_20 = uicontrol( 'String' , price                      , ...
                                  'Parent' , RIGHT_PANEL                , ...
                                  'Style' , 'pushbutton'                , ...
                                  'Callback' , callbr                   , ...
                                  'HorizontalAlignment' , 'center'      , ...
                                  'Units' , 'pixels'                    , ...
                                  'Visible' , 'on'                      , ...
                                  'BackgroundColor' , colour_20         , ... 
                                  'ForegroundColor' , black             , ...
                                  'FontUnits' , 'pixels'                , ...
                                  'FontSize' , 16                       , ...
                                  'Position' , [ 171 , 475 , 90 , 103 ]   ...                                        
                                );
                      
                              
           price = num2str( input_prices(1,21) , '%2.2f');
           price = [ '$' , price ];                                
           callbr = callname( function_name , char(input_button_name(1,21)) );                                    
           button_21 = uicontrol( 'String' , price                      , ...
                                  'Parent' , RIGHT_PANEL                , ...
                                  'Style' , 'pushbutton'                , ...
                                  'Callback' , callbr                   , ...
                                  'HorizontalAlignment' , 'center'      , ...
                                  'Units' , 'pixels'                    , ...
                                  'Visible' , 'on'                      , ...
                                  'BackgroundColor' , colour_21         , ... 
                                  'ForegroundColor' , black             , ...
                                  'FontUnits' , 'pixels'                , ...
                                  'FontSize' , 16                       , ...
                                  'Position' , [ 261 , 475 , 90 , 103 ]   ...                                        
                                );
             
                                
           price = num2str( input_prices(1,22) , '%2.2f');
           price = [ '$' , price ];                          
           callbr = callname( function_name , char(input_button_name(1,22)) );                                    
           button_22 = uicontrol( 'String' , price                     , ...
                                 'Parent' , RIGHT_PANEL                , ...
                                 'Style' , 'pushbutton'                , ...
                                 'Callback' , callbr                   , ...
                                 'HorizontalAlignment' , 'center'      , ...
                                 'Units' , 'pixels'                    , ...
                                 'Visible' , 'on'                      , ...
                                 'BackgroundColor' , colour_22         , ... 
                                 'ForegroundColor' , black             , ...
                                 'FontUnits' , 'pixels'                , ...
                                 'FontSize' , 16                       , ...
                                 'Position' , [ 81 , 317 , 270 , 103 ]   ...                                        
                               );
                  
                               
           price = num2str( input_prices(1,23) , '%2.2f');
           price = [ '$' , price ];  
           callbr = callname( function_name , char(input_button_name(1,23)) );                                    
           button_23 = uicontrol( 'String' , price                     , ...
                                 'Parent' , RIGHT_PANEL                , ...
                                 'Style' , 'pushbutton'                , ...
                                 'Callback' , callbr                   , ...
                                 'HorizontalAlignment' , 'center'      , ...
                                 'Units' , 'pixels'                    , ...
                                 'Visible' , 'on'                      , ...
                                 'BackgroundColor' , colour_23         , ... 
                                 'ForegroundColor' , black             , ...
                                 'FontUnits' , 'pixels'                , ...
                                 'FontSize' , 16                       , ...
                                 'Position' , [ 81 , 159 , 270 , 103 ]   ...                                        
                               );
            
                          
           price = num2str( input_prices(1,24) , '%2.2f');
           price = [ '$' , price ];      
           callbr = callname( function_name , char(input_button_name(1,24)) );                                    
           button_24 = uicontrol( 'String' , price                  , ...
                                 'Parent' , RIGHT_PANEL             , ...
                                 'Style' , 'pushbutton'             , ...
                                 'Callback' , callbr                , ...
                                 'HorizontalAlignment' , 'center'   , ...
                                 'Units' , 'pixels'                 , ...
                                 'Visible' , 'on'                   , ...
                                 'BackgroundColor' , colour_24      , ... 
                                 'ForegroundColor' , black          , ...
                                 'FontUnits' , 'pixels'             , ...
                                 'FontSize' , 16                    , ...
                                 'Position' , [ 1 , 1 , 350 , 88 ]    ...                                        
                               );
                                                     
                                 
            callbr = callname( function_name , char(input_button_name(1,25)) );                                               
            exit_button = uicontrol( 'String' , 'OK'                        , ...
                                     'Parent' , CIGARETTE_FIGURE            , ...
                                     'Style' , 'pushbutton'                 , ...
                                     'Callback' , callbr                    , ...
                                     'HorizontalAlignment' , 'center'       , ...
                                     'Units' , 'pixels'                     , ...
                                     'Visible' , 'on'                       , ...
                                     'Enable' , 'on'                        , ...
                                     'ForegroundColor' , black              , ...
                                     'FontUnits' , 'pixels'                 , ...
                                     'FontSize' , 25                        , ...
                                     'Position' , [ 860 , 30 , 120 , 475  ]   ...                                        
                                   );
                                             
                                             
                                                    
    % buttons
    % =========================== end =====================================
    % =====================================================================
                                                     
              
    
    
    
             
                         
    
    % static text
    %+++++++++++++++++++++++++++++ begin  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                     
                     
           
           text_1 = uicontrol( 'String' , char(input_button_name(1,1)) , ...
                               'Parent' , LEFT_PANEL                   , ...
                               'Style' , 'text'                        , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_1            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontSize' , 21                         , ...
                               'Position' , [ 1 , 578 , 135 , 52 ]       ...                                        
                             );
           
           
           
           text_2 = uicontrol( 'String' , char(input_button_name(1,2)) , ...
                               'Parent' , LEFT_PANEL                   , ...
                               'Style' , 'text'                        , ...
                               'Callback' , callbr                     , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_2            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontSize' , 21                         , ...
                               'Position' , [ 1 , 420 , 134 , 55 ]       ...                                        
                             );
                     
                   
                               
           text_3 = uicontrol( 'String' , char(input_button_name(1,3)) , ...
                               'Parent' , LEFT_PANEL                   , ...
                               'Style' , 'text'                        , ...
                               'Callback' , callbr                     , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_3            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontSize' , 21                         , ...
                               'Position' , [ 1 , 262 , 134 , 55 ]       ...                                        
                             );
                             
                                  
           uicontrol( 'Parent' , LEFT_PANEL                 , ...
                      'Style' , 'text'                      , ...
                      'Units' , 'pixels'                    , ...
                      'Visible' , 'on'                      , ...
                      'BackgroundColor' , colour_4          , ... 
                      'Position' , [ 138 , 578 , 133 , 52 ]   ...                                        
                     );                  
           text_4 = uicontrol( 'String' , char(input_button_name(1,4))  , ...
                               'Parent' , LEFT_PANEL                    , ...
                               'Style' , 'text'                         , ...
                               'HorizontalAlignment' , 'center'         , ...
                               'Units' , 'pixels'                       , ...
                               'Visible' , 'on'                         , ...
                               'BackgroundColor' , colour_4             , ... 
                               'ForegroundColor' , black                , ...
                               'FontUnits' , 'pixels'                   , ...
                               'FontSize' , 21                          , ...
                               'Position' , [ 153 , 580 , 90 , 49 ]       ...                                        
                             );
                             
                             
                             
            uicontrol( 'Parent' , LEFT_PANEL                 , ...
                       'Style' , 'text'                      , ...
                       'Units' , 'pixels'                    , ...
                       'Visible' , 'on'                      , ...
                       'BackgroundColor' , colour_5          , ... 
                       'Position' , [ 137 , 262 , 134 , 55 ]   ...                                        
                      );                  
            text_5 = uicontrol( 'String' , char(input_button_name(1,5)) , ...
                                'Parent' , LEFT_PANEL                   , ...
                                'Style' , 'text'                        , ...
                                'HorizontalAlignment' , 'center'        , ...
                                'Units' , 'pixels'                      , ...
                                'Visible' , 'on'                        , ...
                                'BackgroundColor' , colour_5            , ... 
                                'ForegroundColor' , black               , ...
                                'FontUnits' , 'pixels'                  , ...
                                'FontSize' , 21                         , ...
                                'Position' , [ 157 , 264 , 97 , 51 ]      ...                                        
                              );
                                   
                              
                           
           text_6 = uicontrol( 'String' , char(input_button_name(1,6)) , ...
                               'Parent' , LEFT_PANEL                   , ...
                               'Style' , 'text'                        , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_6            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontWeight' , 'bold'                   , ...
                               'FontSize' , 17                         , ...
                               'Position' , [ 1 , 89 , 89 , 70 ]         ...                                        
                             );
                                
                                    
                              
           text_7 = uicontrol( 'String' , char(input_button_name(1,7)) , ...
                               'Parent' , LEFT_PANEL                   , ...
                               'Style' , 'text'                        , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_7            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontWeight' , 'bold'                   , ...
                               'FontSize' , 17                         , ...
                               'Position' , [ 92 , 89 , 89 , 70 ]        ...                                        
                             );
                                
                               
                          
           text_8 = uicontrol( 'String' , char(input_button_name(1,8)) , ...
                               'Parent' , LEFT_PANEL                   , ...
                               'Style' , 'text'                        , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_8            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontWeight' , 'bold'                   , ...
                               'FontSize' , 17                         , ...
                               'Position' , [ 183 , 89 , 88 , 70 ]       ...                                        
                             );
                             
                                       
           text_9 = uicontrol( 'String' , char(input_button_name(1,9)) , ...
                               'Parent' , MIDDLE_PANEL                 , ...
                               'Style' , 'text'                        , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'BackgroundColor' , colour_9            , ... 
                               'ForegroundColor' , black               , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontSize' , 21                         , ...
                               'Position' , [ 1 , 578 , 89 , 52 ]        ...                                        
                             );
                           
                               
                            
           text_10 = uicontrol( 'String' , char(input_button_name(1,10)) , ...
                                'Parent' , MIDDLE_PANEL                  , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_10            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 1 , 420 , 89 , 55 ]         ...                                        
                              );
                 
                               
                                    
           text_11 = uicontrol( 'String' , char(input_button_name(1,11)) , ...
                                'Parent' , MIDDLE_PANEL                  , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_11            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 1 , 262 , 89 , 55 ]         ...                                        
                              );
                          
                 
           text_12 = uicontrol( 'String' , char(input_button_name(1,12)) , ...
                                'Parent' , MIDDLE_PANEL                  , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_12            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 18                          , ...
                                'Position' , [ 92 , 578 , 99 , 52 ]        ...                                        
                              );
                
                               
           uicontrol( 'Parent' , MIDDLE_PANEL             , ...
                      'Style' , 'text'                    , ...
                      'Units' , 'pixels'                  , ...
                      'Visible' , 'on'                    , ...
                      'BackgroundColor' , colour_13       , ... 
                      'Position' , [ 92 , 420 , 99 , 55 ]   ...                                        
                     );                 
           text_13 = uicontrol( 'String' , char(input_button_name(1,13)) , ...
                                'Parent' , MIDDLE_PANEL                  , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_13            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontWeight' , 'bold'                    , ...
                                'FontSize' , 19                          , ...
                                'Position' , [ 107 , 424 , 68 , 48 ]       ...                                        
                              );
          
                              
                               
           text_14 = uicontrol( 'String' , char(input_button_name(1,14)) , ...
                                'Parent' , MIDDLE_PANEL                  , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_14            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 18                          , ...
                                'Position' , [ 92 , 262 , 99 , 55 ]        ...                                        
                              );
                
                              
                      
          text_15 = uicontrol( 'String' , char(input_button_name(1,15)) , ...
                               'Parent' , MIDDLE_PANEL                  , ...
                               'Style' , 'text'                         , ...
                               'HorizontalAlignment' , 'center'         , ...
                               'Units' , 'pixels'                       , ...
                               'Visible' , 'on'                         , ...
                               'BackgroundColor' , colour_15            , ... 
                               'ForegroundColor' , black                , ...
                               'FontUnits' , 'pixels'                   , ...
                               'FontSize' , 21                          , ...
                               'Position' , [ 1 , 89 , 190 , 70 ]         ...                                        
                             );
                 
                              
                              
           text_16 = uicontrol( 'String' , char(input_button_name(1,16)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_16            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 1 , 578 , 79 , 52 ]         ...                                        
                              );
                          
                              
                              
                                   
           text_17 = uicontrol( 'String' , char(input_button_name(1,17)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_17            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 1 , 420 , 79 , 55 ]         ...                                        
                              );
                 
                              
                              
                              
                                 
           text_18 = uicontrol( 'String' , char(input_button_name(1,18)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_18            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 1 , 262 , 79 , 55 ]         ...                                        
                              );
              
                              
                              
                              
                              
                              
                     
           uicontrol( 'Parent' , RIGHT_PANEL              , ...
                      'Style' , 'text'                    , ...
                      'Units' , 'pixels'                  , ...
                      'Visible' , 'on'                    , ...
                      'BackgroundColor' , colour_19       , ... 
                      'Position' , [ 82 , 578 , 89 , 52 ]   ...                                        
                    );                            
           text_19 = uicontrol( 'String' , char(input_button_name(1,19)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_19            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontWeight' , 'bold'                    , ...
                                'FontSize' , 15                          , ...
                                'Position' , [ 91 , 585 , 70 , 39 ]        ...                                        
                              );
                                 
                               
                              
                              
                              
                            
           uicontrol( 'Parent' , RIGHT_PANEL               , ...
                      'Style' , 'text'                     , ...
                      'Units' , 'pixels'                   , ...
                      'Visible' , 'on'                     , ...
                      'BackgroundColor' , colour_20        , ... 
                      'Position' , [ 173 , 578 , 87 , 52 ]   ...                                        
                    );         
           text_20 = uicontrol( 'String' , char(input_button_name(1,20)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_20            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontWeight' , 'bold'                    , ...
                                'FontSize' , 15                          , ...
                                'Position' , [ 181 , 585 , 70 , 40 ]       ...                                        
                              );
                      
                              
                              
                              
                             
           uicontrol( 'Parent' , RIGHT_PANEL               , ...
                      'Style' , 'text'                     , ...
                      'Units' , 'pixels'                   , ...
                      'Visible' , 'on'                     , ...
                      'BackgroundColor' , colour_21        , ... 
                      'Position' , [ 262 , 578 , 89 , 52 ]   ...                                        
                    );        
           text_21 = uicontrol( 'String' , char(input_button_name(1,21)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_21            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontWeight' , 'bold'                    , ...
                                'FontSize' , 15                          , ...
                                'Position' , [ 267 , 585 , 80 , 40 ]       ...                                        
                              );
             
                                
                              
           uicontrol( 'Parent' , RIGHT_PANEL               , ...
                      'Style' , 'text'                     , ...
                      'Units' , 'pixels'                   , ...
                      'Visible' , 'on'                     , ...
                      'BackgroundColor' , colour_22        , ... 
                      'Position' , [ 82 , 420 , 269 , 55 ]   ...                                        
                    );                   
           text_22 = uicontrol( 'Parent' , RIGHT_PANEL                   , ...
                                'String' , char(input_button_name(1,22)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_22            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 181 , 422 , 66 , 51 ]       ...                                        
                              );
                 
                               
                              
           uicontrol( 'Parent' , RIGHT_PANEL               , ...
                      'Style' , 'text'                     , ...
                      'Units' , 'pixels'                   , ...
                      'Visible' , 'on'                     , ...
                      'BackgroundColor' , colour_23        , ... 
                      'Position' , [ 82 , 262 , 269 , 55 ]   ...                                        
                    );                   
           text_23 = uicontrol( 'String' , char(input_button_name(1,23)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_23            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 180 , 266 , 70 , 50 ]       ...                                        
                              );
           
                              
                              
           uicontrol( 'Parent' , RIGHT_PANEL             , ...
                      'Style' , 'text'                   , ...
                      'Units' , 'pixels'                 , ...
                      'Visible' , 'on'                   , ...
                      'BackgroundColor' , colour_24      , ... 
                      'Position' , [ 1 , 89 , 350 , 70 ]   ...                                        
                    );               
           text_24 = uicontrol( 'String' , char(input_button_name(1,24)) , ...
                                'Parent' , RIGHT_PANEL                   , ...
                                'Style' , 'text'                         , ...
                                'HorizontalAlignment' , 'center'         , ...
                                'Units' , 'pixels'                       , ...
                                'Visible' , 'on'                         , ...
                                'BackgroundColor' , colour_24            , ... 
                                'ForegroundColor' , black                , ...
                                'FontUnits' , 'pixels'                   , ...
                                'FontSize' , 21                          , ...
                                'Position' , [ 135 , 100 , 80 , 55 ]       ...                                        
                              );
                                                     
                                 
    
    % static text
    %++++++++++++++++++++++++++++++  end  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++      
    
    
    
    
                        
    
    % dynamic text
    %+++++++++++++++++++++++++++++ begin  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                     
          display = uicontrol( 'String' , ''                           , ...
                               'Parent' , CIGARETTE_FIGURE             , ...
                               'Style' , 'text'                        , ...
                               'HorizontalAlignment' , 'center'        , ...
                               'Units' , 'pixels'                      , ...
                               'Visible' , 'on'                        , ...
                               'Enable' , 'on'                         , ...
                               'ForegroundColor' , black               , ...
                               'BackgroundColor' , colour_display      , ...
                               'FontUnits' , 'pixels'                  , ...
                               'FontSize' , 18                         , ...
                               'Position' , [ 860 , 506 , 119 , 154  ]   ...                                        
                              );
                                         
    
      
    % dynamic text
    %++++++++++++++++++++++++++++++  end  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++      
    
    
    
    
    
              data_list  = [  button_1     , button_2  , button_3  , ...  % LEFT_PANEL
                              button_4     , button_5  , ...              % LEFT_PANEL
                              button_6     , button_7  , button_8  , ...  % LEFT_PANEL
                              button_9     , button_10 , button_11 , ...  % MIDDLE_PANEL
                              button_12    , button_13 , button_14 , ...  % MIDDLE_PANEL
                              button_15    , ...                          % MIDDLE_PANEL
                              button_16    , button_17 , button_18 , ...  % RIGHT_PANEL
                              button_19    , button_20 , button_21 , ...  % RIGHT_PANEL
                              button_22    , ...                          % RIGHT_PANEL
                              button_23    , ...                          % RIGHT_PANEL
                              button_24    , ...                          % RIGHT_PANEL
                              exit_button  , ...                          % CIGARETTE_FIGURE
                              display                                     % CIGARETTE_FIGURE
                           ];
    
              set( CIGARETTE_FIGURE , 'UserData' , data_list );
              set( CIGARETTE_FIGURE , 'Visible' , 'off' );
              
              set( CIGARETTE_FIGURE , 'CloseRequestFcn' , 'closereq' );
              set( CIGARETTE_FIGURE , 'Backingstore' , 'on' );
              
              watchoff( mouse_pointer );
    
output = CIGARETTE_FIGURE;
