 function output = customer_figure( title )
        
        mouse_pointer = watchon();
            
        % define colour
        grey = [ 0.5 , 0.5 , 0.5 ];
        white = [ 1 1 1 ];
        black = [ 0 0 0 ];
        blue = [ 0.1 0.15 1 ];
        orange = [ .9 0.4 0.2 ];
        
        pale_green =  [ 0.9 1 0.9];
        pale_orange = [ 1 1 .95 ];
        pale_yellow = [ .9 0.9 0.8 ];
        pale_grey = [ 0.9 0.9 0.9 ];
        
        
        screen_details = get(0,'ScreenSize');
        fig_x = 1000;
        fig_y = 660; 
     
        
        CUSTOMER_FIGURE = figure( 'Name' , title , ...
                                  'Units', 'pixels',...
                                  'resize', 'off', ...
                                  'NumberTitle' , 'off' , ...
                                  'Visible' , 'off' , ...
                                  'position', [ 1040 , abs( screen_details(4) - 660 - 75 ) ,  1000 , 660 ] ...
                                );
    
                        
                                
        colordef( CUSTOMER_FIGURE , 'black' );  
        
        
        % panels  
        % &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        % &&&&&&&&&&&&&&&&&&&&&&&&& beginning &&&&&&&&&&&&&&&&&&&&&&&
           
        
        
            cust_input_money_panel = uipanel( 'Parent' , CUSTOMER_FIGURE , ...
                                              'Title' , 'Input Amount' , ...
                                              'FontName' , 'Arial' , ...
                                              'FontUnits' , 'points' , ...
                                              'FontWeight' , 'bold' , ...
                                              'FontSize' , 18 , ...
                                              'Units' , 'pixels' , ...
                                              'Visible' , 'on' , ...
                                              'BackgroundColor' , grey , ...
                                              'Position' , [ 20 , 450 , 310 , 190 ]  ...
                                            );
                                        
            cust_total_panel = uipanel( 'Parent' , CUSTOMER_FIGURE , ...
                                        'Title' , 'Total Amount' , ...
                                        'FontName' , 'Arial' , ...
                                        'FontUnits' , 'points' , ...
                                        'FontWeight' , 'bold' , ...
                                        'FontSize' , 18 , ...
                                        'Units' , 'pixels' , ...
                                        'Visible' , 'on' , ...
                                        'BackgroundColor' , grey , ...
                                        'Position' , [ 20 , 235 , 310 , 190 ]  ...
                                      );    
                                  
                                      
            cust_change_panel = uipanel( 'Parent' , CUSTOMER_FIGURE , ...
                                         'Title' , 'Change' , ...
                                         'FontName' , 'Arial' , ...
                                         'FontUnits' , 'points' , ...
                                         'FontWeight' , 'bold' , ...
                                         'FontSize' , 18 , ...
                                         'Units' , 'pixels' , ...
                                         'Visible' , 'on' , ...
                                         'BackgroundColor' , grey , ...
                                         'Position' , [ 20 , 20 , 310 , 190 ]  ...
                                       );                     
                                       
                                       
                                       
                                       
                                       
            cust_items_panel = uipanel( 'Parent' , CUSTOMER_FIGURE , ...
                                        'Title' , 'Items' , ...
                                        'FontName' , 'Arial' , ...
                                        'FontUnits' , 'points' , ...
                                        'FontWeight' , 'bold' , ...
                                        'FontSize' , 18 , ...
                                        'Units' , 'pixels' , ...
                                        'Visible' , 'on' , ...
                                        'BackgroundColor' , grey , ...
                                        'Position' , [ 350 , 20 , 630 , 620 ]  ...
                                      );
            
                                                                  
                                       
        % panels                      
        % &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        % &&&&&&&&&&&&&&&&&&&&&&&&& end &&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        
        
        
        
        
        
        % static text
        % @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        % @@@@@@@@@@@@@@@@@@@@@@@@@ beginning @@@@@@@@@@@@@@@@@@@@@@@
        
        
            % 'a' is the background for the text                          
            a = uicontrol( 'Parent' , cust_input_money_panel  , ...
                           'Style' , 'text' , ...
                           'Units' , 'pixels' , ...
                           'BackgroundColor' , pale_green , ...
                           'Visible' , 'on' , ...
                           'Tag' , 'input' , ...
                           'HorizontalAlignment' , 'center' , ...
                           'FontName' , 'Tahoma' , ...
                           'FontUnits' , 'pixels' , ...
                           'FontSize' , 50 , ...
                           'Position' , [ 20 , 20 , 270 , 130 ] ...                                        
                         );                      
            cust_input = uicontrol( 'Parent' , cust_input_money_panel  , ...
                                    'Style' , 'text' , ...
                                    'Units' , 'pixels' , ...
                                    'BackgroundColor' , pale_green , ...
                                    'ForegroundColor' , black , ...
                                    'Visible' , 'on' , ...
                                    'Tag' , 'input' , ...
                                    'HorizontalAlignment' , 'center' , ...
                                    'FontName' , 'Tahoma' , ...
                                    'FontUnits' , 'pixels' , ...
                                    'FontSize' , 50 , ...
                                    'Position' , [ 20 , 55 , 270 , 65 ] ...                                        
                                  );
                                          
            % 'b' is the background for the text    
            b = uicontrol( 'Parent' , cust_total_panel  , ...
                           'Style' , 'text' , ...
                           'Units' , 'pixels' , ...
                           'BackgroundColor' , pale_orange , ... 
                           'Tag' , 'input' , ...
                           'HorizontalAlignment' , 'center' , ...
                           'FontName' , 'Tahoma' , ...
                           'FontUnits' , 'pixels' , ...
                           'FontSize' , 50 , ...
                           'Position' , [ 20 , 20 , 270 , 130 ] ...                                        
                         );
            cust_total = uicontrol( 'Parent' , cust_total_panel  , ...
                                    'Style' , 'text' , ...
                                    'Units' , 'pixels' , ...
                                    'BackgroundColor' , pale_orange , ... 
                                    'ForegroundColor' , orange , ...
                                    'Tag' , 'input' , ...
                                    'HorizontalAlignment' , 'center' , ...
                                    'FontName' , 'Tahoma' , ...
                                    'FontUnits' , 'pixels' , ...
                                    'FontSize' , 50 , ...
                                    'Position' , [ 20 , 55 , 270 , 65 ] ...                                        
                                  );
                                        
            % 'c' is the background for the text                       
            c = uicontrol( 'Parent' , cust_change_panel , ...
                           'Style' , 'text' , ...
                           'Units' , 'pixels' , ...
                           'BackgroundColor' , white , ...
                           'Visible' , 'on' , ...
                           'Tag' , 'input' , ...
                           'HorizontalAlignment' , 'center' , ...
                           'FontName' , 'Tahoma' , ...
                           'FontUnits' , 'pixels' , ...
                           'FontSize' , 50 , ...
                           'Position' , [ 20 , 20 , 270 , 130 ] ...                                        
                         );                      
            cust_change = uicontrol( 'Parent' , cust_change_panel , ...
                                     'Style' , 'text' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , white , ...
                                     'ForegroundColor' , blue , ...
                                     'Visible' , 'on' , ...
                                     'Tag' , 'input' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'FontName' , 'Tahoma' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 50 , ...
                                     'Position' , [ 20 , 55 , 270 , 65 ] ...                                        
                                   );
                               
                                   
                                   
           % What the customer see
           % -------------------------------------- 
           cust_display_1 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 556 , 260 , 31 ] ...                                        
                                     );
                               
                                   
           cust_display_2 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 556 , 260 , 31 ] ...                                        
                                     );
                               
           
           cust_display_3 = uicontrol(  'String' , '' , ...
                                        'Parent' , cust_items_panel , ...
                                        'Style' , 'text' , ...
                                        'Units' , 'pixels' , ...
                                        'BackgroundColor' , grey , ...
                                        'ForegroundColor' , black , ...
                                        'Visible' , 'on' , ...
                                        'Tag' , 'input' , ...
                                        'HorizontalAlignment' , 'left' , ...
                                        'FontName' , 'Courier New' , ...
                                        'FontUnits' , 'pixels' , ...
                                        'FontSize' , 13 , ...
                                        'Position' , [ 35 , 519 , 260 , 31 ] ...                                        
                                     );
                               
           
           cust_display_4 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 519 , 260 , 31 ] ...                                        
                                     );
                               
           
           cust_display_5 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 482 , 260 , 31 ] ...                                        
                                     );
                               
           
           cust_display_6 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 482 , 260 , 31 ] ...                                        
                                     );
                               
           
           cust_display_7 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 446 , 260 , 31 ] ...                                        
                                     );
                               
           
           cust_display_8 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 446 , 260 , 31 ] ...                                        
                                     );
                               
                                   
          cust_display_9 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 13 , ...
                                      'Position' , [ 35 , 410 , 260 , 31 ] ...                                        
                                    );
           
                                    
          cust_display_10 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 13 , ...
                                      'Position' , [ 340 , 410 , 260 , 31 ] ...                                        
                                    );
              
                                   
          cust_display_11 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 13 , ...
                                      'Position' , [ 35 , 374 , 260 , 31 ] ...                                        
                                    );
           
                                    
          cust_display_12 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 13 , ...
                                      'Position' , [ 340 , 374 , 260 , 31 ] ...                                        
                                    );
                                                                                         
                            
          cust_display_13 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 13 , ...
                                      'Position' , [ 35 , 338 , 260 , 31 ] ...                                        
                                    );
           
                                    
          cust_display_14 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 13 , ...
                                      'Position' , [ 340 , 338  , 260 , 31 ] ...                                        
                                    );
                                                                                         
                                      
          cust_display_15 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 302 , 260 , 31 ] ...                                        
                                     );
           
                                    
          cust_display_16 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 302 , 260 , 31 ] ...                                        
                                     );
                              
                                    
          cust_display_17 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 266 , 260 , 31 ] ...                                        
                                     );
           
                                    
          cust_display_18 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 266 , 260 , 31 ] ...                                        
                                     );
                                       
                                     
          cust_display_19 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 230 , 260 , 31 ] ...                                        
                                     );
                                       
                                     
          cust_display_20 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 230 , 260 , 31 ] ...                                        
                                     );
                                       
                                     
          cust_display_21 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 194 , 260 , 31 ] ...                                        
                                     );
           
                                    
          cust_display_22 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 194 , 260 , 31 ] ...                                        
                                     );
                                       
                                         
          cust_display_23 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 158 , 260 , 31 ] ...                                        
                                     );
           
                                    
          cust_display_24 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 158 , 260 , 31 ] ...                                        
                                     );
                                                                                                      
                            
          cust_display_25 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 122 , 260 , 31 ] ...                                        
                                     );
           
                                    
          cust_display_26 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 122 , 260 , 31 ] ...                                        
                                     );           
                                     

          cust_display_27 = uicontrol( 'String' , '' , ...
                                      'Parent' , cust_items_panel , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , grey , ...
                                      'ForegroundColor' , black , ...
                                      'Visible' , 'on' , ...
                                      'Tag' , 'input' , ...
                                      'HorizontalAlignment' , 'left' , ...
                                      'FontName' , 'Courier New' , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontSize' , 10 , ...
                                      'Position' , [ 35 , 86 , 260 , 31 ] ...                                        
                                    );

                            
          cust_display_28 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 86 , 260 , 31 ] ...                                        
                                     );
           
                                    
          cust_display_29 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 50 , 260 , 31 ] ...                                        
                                     ); 

                            
          cust_display_30 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 50 , 260 , 31 ] ...                                        
                                     );
          
                                            
          cust_display_31 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 35 , 14 , 260 , 31 ] ...                                        
                                     ); 

                            
          cust_display_32 = uicontrol( 'String' , '' , ...
                                       'Parent' , cust_items_panel , ...
                                       'Style' , 'text' , ...
                                       'Units' , 'pixels' , ...
                                       'BackgroundColor' , grey , ...
                                       'ForegroundColor' , black , ...
                                       'Visible' , 'on' , ...
                                       'Tag' , 'input' , ...
                                       'HorizontalAlignment' , 'left' , ...
                                       'FontName' , 'Courier New' , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 340 , 14 , 260 , 31 ] ...                                        
                                     );
                                
                                              
        % static text
        % @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        % @@@@@@@@@@@@@@@@@@@@@@@@@@@@ end @@@@@@@@@@@@@@@@@@@@@@@@@@
                             
                             
              % list of buttons
              data_list  = [ cust_total      , cust_input      , cust_change      , ...  % 1  , 2  , 3
                             cust_display_1  , cust_display_2  , cust_display_3   , ...  % 4  , 5  , 6
                             cust_display_4  , cust_display_5  , cust_display_6   , ...  % 7  , 8  , 9
                             cust_display_7  , cust_display_8  , cust_display_9   , ...  % 10 , 11 , 12
                             cust_display_10 , cust_display_11 , cust_display_12  , ...  % 13 , 14 , 15 
                             cust_display_13 , cust_display_14 , cust_display_15  , ...  % 16 , 17 , 18
                             cust_display_16 , cust_display_17 , cust_display_18  , ...  % 19 , 20 , 21
                             cust_display_19 , cust_display_20 , cust_display_21  , ...  % 22 , 23 , 24
                             cust_display_22 , cust_display_23 , cust_display_24  , ...  % 25 , 26 , 27 
                             cust_display_25 , cust_display_26 , cust_display_27  , ...  % 28 , 29 , 30
                             cust_display_28 , cust_display_29 , cust_display_30  , ...  % 31 , 32 , 33 
                             cust_display_31 , cust_display_32   ...                     % 34 , 35
                           ];                                                                           
                    
              set( CUSTOMER_FIGURE , 'UserData' , data_list );
              set( data_list , 'Enable' , 'on' );
              watchoff( mouse_pointer );

output = CUSTOMER_FIGURE;

