% precondition: input_button_name is a string array of size 19
%              multi_trip_prices is an int array of size 8
%              single_trip_price is an int array of size 8
%              daytrip_price is an int array of size 3

function output = internet( function_name , input_button_name )

    mouse_pointer = watchon();
    format short g;
   
    %panel construction variables
    SCREEN_DETAILS = get(0,'ScreenSize');
    fig_x = 950;
    fig_y = 690;
    
    panel_height = 100;
    panel_gap = 12;

    standard_height = 28;
    panel_height_ref = 10;

    button_gap = 5;    

    INTERNET_FIGURE = figure( 'Name' , 'Internet Access' , ...
                              'Units', 'pixels'          , ...
                              'resize', 'off'            , ...
                              'NumberTitle' , 'off'      , ...
                              'Visible' , 'on'           , ...
                              'position', [ 10 , abs( SCREEN_DETAILS(4) - fig_y - 45 ) ,  fig_x , fig_y ] ...
                            );
                       
    colordef( INTERNET_FIGURE  , 'black' );
    
    
    
    blue = [ 0.1 0.15 1 ];
    orange = [ .9 0.4 0.2 ];
    red = [ 1 0.22 0 ];
    green =  [ 0 1 0.1 ];
    grey = [ 0.5 0.5 0.5 ];
    white = [ 1 1 1 ];
    black = [ 0 0 0 ];
    purple = [ 0.5 0.2 1 ];
    dark_green = [ 0.15 0.22 0.22 ];
    
    
    pale_green =  [ 0.9 1 0.9];
    pale_orange = [ 1 1 .95 ];
    pale_yellow = [ .9 0.9 0.8 ];
    pale_grey = [ 0.9 0.9 0.9 ];
    
    
    % panel
    %----------------------------  begin  ---------------------------------
    %----------------------------------------------------------------------
   
    
                         
     PANEL_1 = uipanel( 'Title' , 'Computer 1'                                                   , ...
                        'Parent' , INTERNET_FIGURE                                               , ...
                        'FontName' , 'Arial'                                                     , ...
                        'FontUnits' , 'points'                                                   , ...
                        'FontWeight' , 'bold'                                                    , ...
                        'FontSize' , 15                                                          , ...
                        'Units' , 'pixels'                                                       , ...
                        'Visible' , 'on'                                                         , ...
                        'BackgroundColor' , grey                                                 , ...
                        'ForegroundColor' , blue                                                 , ...
                        'Position' , [ 30 , 15+5*panel_height+5*panel_gap , 750 , panel_height ]   ...
                      );  
                       
     PANEL_2 = uipanel( 'Title' , 'Computer 2'                                                   , ...
                        'Parent' , INTERNET_FIGURE                                               , ...
                        'FontName' , 'Arial'                                                     , ...
                        'FontUnits' , 'points'                                                   , ...
                        'FontWeight' , 'bold'                                                    , ...
                        'FontSize' , 15                                                          , ...
                        'Units' , 'pixels'                                                       , ...
                        'Visible' , 'on'                                                         , ...
                        'BackgroundColor' , grey                                                 , ...
                        'ForegroundColor' , orange                                               , ...
                        'Position' , [ 30 , 15+4*panel_height+4*panel_gap , 750 , panel_height ]   ...
                      );  
                            
     PANEL_3 = uipanel( 'Title' , 'Computer 3'                                                   , ...
                        'Parent' , INTERNET_FIGURE                                               , ...
                        'FontName' , 'Arial'                                                     , ...
                        'FontUnits' , 'points'                                                   , ...
                        'FontWeight' , 'bold'                                                    , ...
                        'FontSize' , 15                                                          , ...
                        'Units' , 'pixels'                                                       , ...
                        'Visible' , 'on'                                                         , ...
                        'BackgroundColor' , grey                                                 , ...
                        'ForegroundColor' , green                                                , ...
                        'Position' , [ 30 , 15+3*panel_height+3*panel_gap , 750 , panel_height ]   ...
                      );  
                                
     PANEL_4 = uipanel( 'Title' , 'Computer 4'                                                   , ...
                        'Parent' , INTERNET_FIGURE                                               , ...
                        'FontName' , 'Arial'                                                     , ...
                        'FontUnits' , 'points'                                                   , ...
                        'FontWeight' , 'bold'                                                    , ...
                        'FontSize' , 15                                                          , ...
                        'Units' , 'pixels'                                                       , ...
                        'Visible' , 'on'                                                         , ...
                        'BackgroundColor' , grey                                                 , ...
                        'ForegroundColor' , red                                                  , ...
                        'Position' , [ 30 , 15+2*panel_height+2*panel_gap , 750 , panel_height ]   ...
                      );  
                         
     PANEL_5 = uipanel( 'Title' , 'Computer 5'                                               , ...
                        'Parent' , INTERNET_FIGURE                                           , ...
                        'FontName' , 'Arial'                                                 , ...
                        'FontUnits' , 'points'                                               , ...
                        'FontWeight' , 'bold'                                                , ...
                        'FontSize' , 15                                                      , ...
                        'Units' , 'pixels'                                                   , ...
                        'Visible' , 'on'                                                     , ...
                        'BackgroundColor' , grey                                             , ...
                        'ForegroundColor' ,  purple                                          , ...
                        'Position' , [ 30 , 15+panel_height+panel_gap , 750 , panel_height ]   ...
                      );  
                            
     PANEL_6 = uipanel( 'Title' , 'Computer 6'                        , ...
                        'Parent' , INTERNET_FIGURE                    , ...
                        'FontName' , 'Arial'                          , ...
                        'FontUnits' , 'points'                        , ...
                        'FontWeight' , 'bold'                         , ...
                        'FontSize' , 15                               , ...
                        'Units' , 'pixels'                            , ...
                        'Visible' , 'on'                              , ...
                        'BackgroundColor' , grey                      , ...
                        'ForegroundColor' , dark_green                , ...
                        'Position' , [ 30 , 15 , 750 , panel_height ]   ...
                      );  


    
    % panel
    %----------------------------  end  ---------------------------------
    %--------------------------------------------------------------------                     
                           
                   
   



    
    
    % buttons
    % ============================ begin ==================================
    % =====================================================================
 
                                    
                               
            callbr = callname( function_name , char(input_button_name(1,1)) );                                               
            reset_1 = uicontrol( 'String' , char(input_button_name(1,1))                                                   , ...
                                 'Parent' , PANEL_1                                                                        , ...
                                 'Style' , 'pushbutton'                                                                    , ...
                                 'Callback' , callbr                                                                       , ...
                                 'HorizontalAlignment' , 'center'                                                          , ...
                                 'Units' , 'pixels'                                                                        , ...
                                 'Visible' , 'on'                                                                          , ...
                                 'Enable' , 'on'                                                                           , ...
                                 'ForegroundColor' , black                                                                 , ...
                                 'FontUnits' , 'pixels'                                                                    , ...
                                 'FontWeight' , 'bold'                                                                     , ...
                                 'FontSize' , 15                                                                           , ...
                                 'Position' , [ 30 , panel_height_ref+standard_height+button_gap , 170 , standard_height ]   ...                                        
                                );
                               
            callbr = callname( function_name , char(input_button_name(1,4)) );                                               
            reset_2 = uicontrol( 'String' , char(input_button_name(1,4))                                                   , ...
                                 'Parent' , PANEL_2                                                                        , ...
                                 'Style' , 'pushbutton'                                                                    , ...
                                 'Callback' , callbr                                                                       , ...
                                 'HorizontalAlignment' , 'center'                                                          , ...                                  
                                 'Units' , 'pixels'                                                                        , ...
                                 'Visible' , 'on'                                                                          , ...
                                 'Enable' , 'on'                                                                           , ...
                                 'ForegroundColor' , black                                                                 , ...
                                 'FontUnits' , 'pixels'                                                                    , ...
                                 'FontWeight' , 'bold'                                                                     , ...
                                 'FontSize' , 15                                                                           , ...
                                 'Position' , [ 30 , panel_height_ref+standard_height+button_gap , 170 , standard_height ]   ...                                   
                               );                  

            callbr = callname( function_name , char(input_button_name(1,7)) );                                               
            reset_3 = uicontrol( 'String' , char(input_button_name(1,7))                                                   , ...
                                 'Parent' , PANEL_3                                                                        , ...
                                 'Style' , 'pushbutton'                                                                    , ...
                                 'Callback' , callbr                                                                       , ...
                                 'HorizontalAlignment' , 'center'                                                          , ...
                                 'Units' , 'pixels'                                                                        , ...
                                 'Visible' , 'on'                                                                          , ...
                                 'Enable' , 'on'                                                                           , ...
                                 'ForegroundColor' , black                                                                 , ...
                                 'FontUnits' , 'pixels'                                                                    , ...
                                 'FontWeight' , 'bold'                                                                     , ...
                                 'FontSize' , 15                                                                           , ...
                                 'Position' , [ 30 , panel_height_ref+standard_height+button_gap , 170 , standard_height ]   ...
                               );                     

            callbr = callname( function_name , char(input_button_name(1,10)) );                                               
            reset_4 = uicontrol( 'String' , char(input_button_name(1,10))                                                  , ...
                                 'Parent' , PANEL_4                                                                        , ...
                                 'Style' , 'pushbutton'                                                                    , ...
                                 'Callback' , callbr                                                                       , ...
                                 'HorizontalAlignment' , 'center'                                                          , ...
                                 'Units' , 'pixels'                                                                        , ...
                                 'Visible' , 'on'                                                                          , ...
                                 'Enable' , 'on'                                                                           , ...
                                 'ForegroundColor' , black                                                                 , ...
                                 'FontUnits' , 'pixels'                                                                    , ...
                                 'FontWeight' , 'bold'                                                                     , ...
                                 'FontSize' , 15                                                                           , ...
                                 'Position' , [ 30 , panel_height_ref+standard_height+button_gap , 170 , standard_height ]   ...                                        
                               );
   
            callbr = callname( function_name , char(input_button_name(1,13)) );                                               
            reset_5 = uicontrol( 'String' , char(input_button_name(1,13))                                                  , ...
                                 'Parent' , PANEL_5                                                                        , ...
                                 'Style' , 'pushbutton'                                                                    , ...
                                 'Callback' , callbr                                                                       , ...
                                 'HorizontalAlignment' , 'center'                                                          , ...
                                 'Units' , 'pixels'                                                                        , ...
                                 'Visible' , 'on'                                                                          , ...
                                 'Enable' , 'on'                                                                           , ...
                                 'ForegroundColor' , black                                                                 , ...
                                 'FontUnits' , 'pixels'                                                                    , ...
                                 'FontWeight' , 'bold'                                                                     , ...
                                 'FontSize' , 15                                                                           , ...
                                 'Position' , [ 30 , panel_height_ref+standard_height+button_gap , 170 , standard_height ]   ...                                        
                               );                             
                                   
            callbr = callname( function_name , char(input_button_name(1,16)) );                                               
            reset_6 = uicontrol( 'String' , char(input_button_name(1,16))                                                  , ...
                                 'Parent' , PANEL_6                                                                        , ...
                                 'Style' , 'pushbutton'                                                                    , ...
                                 'Callback' , callbr                                                                       , ...
                                 'HorizontalAlignment' , 'center'                                                          , ...
                                 'Units' , 'pixels'                                                                        , ...
                                 'Visible' , 'on'                                                                          , ...
                                 'Enable' , 'on'                                                                           , ...
                                 'ForegroundColor' , black                                                                 , ...
                                 'FontUnits' , 'pixels'                                                                    , ...
                                 'FontWeight' , 'bold'                                                                     , ...
                                 'FontSize' , 15                                                                           , ...
                                 'Position' , [ 30 , panel_height_ref+standard_height+button_gap , 170 , standard_height ]   ...                                        
                               );


           
            callbr = callname( function_name , char(input_button_name(1,2)) );                                               
            start_1 = uicontrol( 'String' , char(input_button_name(1,2))                                                    , ...
                                 'Parent' , PANEL_1                                                                         , ...
                                 'Style' , 'pushbutton'                                                                     , ...
                                 'Callback' , callbr                                                                        , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'Enable' , 'on'                                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 15                                                                            , ...
                                 'Position' , [ 230 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                        
                                );
                           
            callbr = callname( function_name , char(input_button_name(1,5)) );                                               
            start_2 = uicontrol( 'String' , char(input_button_name(1,5))                                                    , ...
                                 'Parent' , PANEL_2                                                                         , ...
                                 'Style' , 'pushbutton'                                                                     , ...
                                 'Callback' , callbr                                                                        , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'Enable' , 'on'                                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 15                                                                            , ...
                                 'Position' , [ 230 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...
                                );
                     
            callbr = callname( function_name , char(input_button_name(1,8)) );                                               
            start_3 = uicontrol( 'String' , char(input_button_name(1,8))                                                    , ...
                                 'Parent' , PANEL_3                                                                         , ...
                                 'Style' , 'pushbutton'                                                                     , ...
                                 'Callback' , callbr                                                                        , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'Enable' , 'on'                                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 15                                                                            , ...
                                 'Position' , [ 230 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                                );
                            
            callbr = callname( function_name , char(input_button_name(1,11)) );                                               
            start_4 = uicontrol( 'String' , char(input_button_name(1,11))                                                   , ...
                                 'Parent' , PANEL_4                                                                         , ...
                                 'Style' , 'pushbutton'                                                                     , ...
                                 'Callback' , callbr                                                                        , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'Enable' , 'on'                                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 15                                                                            , ...
                                 'Position' , [ 230 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                               );
                            
            callbr = callname( function_name , char(input_button_name(1,14)) );                                               
            start_5 = uicontrol( 'String' , char(input_button_name(1,14))                                                   , ...
                                 'Parent' , PANEL_5                                                                         , ...
                                 'Style' , 'pushbutton'                                                                     , ...
                                 'Callback' , callbr                                                                        , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'Enable' , 'on'                                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 15                                                                            , ...
                                 'Position' , [ 230 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                               );
                            
            callbr = callname( function_name , char(input_button_name(1,17)) );                                               
            start_6 = uicontrol( 'String' , char(input_button_name(1,17))                                                   , ...
                                 'Parent' , PANEL_6                                                                         , ...
                                 'Style' , 'pushbutton'                                                                     , ...
                                 'Callback' , callbr                                                                        , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'Enable' , 'on'                                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 15                                                                            , ...
                                 'Position' , [ 230 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                               );


                   
            callbr = callname( function_name , char(input_button_name(1,3)) );                                               
            end_1 = uicontrol( 'String' , char(input_button_name(1,3))                                                    , ...
                               'Parent' , PANEL_1                                                                         , ...
                               'Style' , 'pushbutton'                                                                     , ...
                               'Callback' , callbr                                                                        , ...
                               'HorizontalAlignment' , 'center'                                                           , ...
                               'Units' , 'pixels'                                                                         , ...
                               'Visible' , 'on'                                                                           , ...
                               'Enable' , 'off'                                                                           , ...
                               'ForegroundColor' , black                                                                  , ...
                               'FontUnits' , 'pixels'                                                                     , ...
                               'FontSize' , 15                                                                            , ...
                               'Position' , [ 400 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                        
                              );
                         
            callbr = callname( function_name , char(input_button_name(1,6)) );                                               
            end_2 = uicontrol( 'String' , char(input_button_name(1,6))                                                    , ...
                               'Parent' , PANEL_2                                                                         , ...
                               'Style' , 'pushbutton'                                                                     , ...
                               'Callback' , callbr                                                                        , ...
                               'HorizontalAlignment' , 'center'                                                           , ...
                               'Units' , 'pixels'                                                                         , ...
                               'Visible' , 'on'                                                                           , ...
                               'Enable' , 'off'                                                                           , ...
                               'ForegroundColor' , black                                                                  , ...
                               'FontUnits' , 'pixels'                                                                     , ...
                               'FontSize' , 15                                                                            , ...
                               'Position' , [ 400 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                        
                              );
                          
            callbr = callname( function_name , char(input_button_name(1,9)) );                                               
            end_3 = uicontrol( 'String' , char(input_button_name(1,9))                                                    , ...
                               'Parent' , PANEL_3                                                                         , ...
                               'Style' , 'pushbutton'                                                                     , ...
                               'Callback' , callbr                                                                        , ...
                               'HorizontalAlignment' , 'center'                                                           , ...
                               'Units' , 'pixels'                                                                         , ...
                               'Visible' , 'on'                                                                           , ...
                               'Enable' , 'off'                                                                           , ...
                               'ForegroundColor' , black                                                                  , ...
                               'FontUnits' , 'pixels'                                                                     , ...
                               'FontSize' , 15                                                                            , ...
                               'Position' , [ 400 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                        
                             );
                           
            callbr = callname( function_name , char(input_button_name(1,12)) );                                               
            end_4 = uicontrol( 'String' , char(input_button_name(1,12))                                                   , ...
                               'Parent' , PANEL_4                                                                         , ...
                               'Style' , 'pushbutton'                                                                     , ...
                               'Callback' , callbr                                                                        , ...
                               'HorizontalAlignment' , 'center'                                                           , ...
                               'Units' , 'pixels'                                                                         , ...
                               'Visible' , 'on'                                                                           , ...
                               'Enable' , 'off'                                                                           , ...
                               'ForegroundColor' , black                                                                  , ...
                               'FontUnits' , 'pixels'                                                                     , ...
                               'FontSize' , 15                                                                            , ...
                               'Position' , [ 400 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                             );
                           
            callbr = callname( function_name , char(input_button_name(1,15)) );                                               
            end_5 = uicontrol( 'String' , char(input_button_name(1,15))                                                   , ...
                               'Parent' , PANEL_5                                                                         , ...
                               'Style' , 'pushbutton'                                                                     , ...
                               'Callback' , callbr                                                                        , ...
                               'HorizontalAlignment' , 'center'                                                           , ...
                               'Units' , 'pixels'                                                                         , ...
                               'Visible' , 'on'                                                                           , ...
                               'Enable' , 'off'                                                                           , ...
                               'ForegroundColor' , black                                                                  , ...
                               'FontUnits' , 'pixels'                                                                     , ...
                               'FontSize' , 15                                                                            , ...
                               'Position' , [ 400 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                             );
                           
            callbr = callname( function_name , char(input_button_name(1,18)) );                                               
            end_6 = uicontrol( 'String' , char(input_button_name(1,18))                                                   , ...
                               'Parent' , PANEL_6                                                                         , ...
                               'Style' , 'pushbutton'                                                                     , ...
                               'Callback' , callbr                                                                        , ...
                               'HorizontalAlignment' , 'center'                                                           , ...
                               'Units' , 'pixels'                                                                         , ...
                               'Visible' , 'on'                                                                           , ...
                               'Enable' , 'off'                                                                           , ...
                               'ForegroundColor' , black                                                                  , ...
                               'FontUnits' , 'pixels'                                                                     , ...
                               'FontSize' , 15                                                                            , ...
                               'Position' , [ 400 , panel_height_ref+standard_height+button_gap , 140 , standard_height ]   ...                                       
                             );
                           
                            
                             
            callbr = callname( function_name , char(input_button_name(1,19)) );                                               
            undo_button = uicontrol( 'String' , char(input_button_name(1,19))                                   , ...
                                     'Parent' , INTERNET_FIGURE                                                  , ...
                                     'Style' , 'pushbutton'                                                      , ...
                                     'Callback' , callbr                                                         , ...
                                     'HorizontalAlignment' , 'center'                                            , ...
                                     'Units' , 'pixels'                                                          , ...
                                     'Visible' , 'on'                                                            , ...
                                     'Enable' , 'on'                                                             , ...
                                     'ForegroundColor' , black                                                   , ...
                                     'FontUnits' , 'pixels'                                                      , ...
                                     'FontSize' , 25                                                             , ...
                                     'Position' , [ 800 , 15+5*panel_height+5*panel_gap , 120 , panel_height  ]    ...                                        
                                   );
                               
            callbr = callname( function_name , char(input_button_name(1,20)) );                                               
            exit_button = uicontrol( 'String' , 'OK'                                              , ...
                                     'Parent' , INTERNET_FIGURE                                   , ...
                                     'Style' , 'pushbutton'                                       , ...
                                     'Callback' , callbr                                          , ...
                                     'HorizontalAlignment' , 'center'                             , ...
                                     'Units' , 'pixels'                                           , ...
                                     'Visible' , 'on'                                             , ...
                                     'Enable' , 'on'                                              , ...
                                     'ForegroundColor' , black                                    , ...
                                     'FontUnits' , 'pixels'                                       , ...
                                     'FontSize' , 25                                              , ...
                                     'Position' , [ 800 , 15 , 120 , 5*panel_height+4*panel_gap ]   ...                                        
                                   );
                                            
                                                
                                             
                                                    
    % buttons
    % =========================== end =====================================
    % =====================================================================
                                                     
              
             
        
    
    
    % dynamic text
    %+++++++++++++++++++++++++++++ begin  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                     
                       
                    
                                                 
            start_time_1 = uicontrol( 'String' , ''                                                   , ...
                                      'Parent' , PANEL_1                                              , ...
                                      'Style' , 'text'                                                , ...
                                      'HorizontalAlignment' , 'center'                                , ...
                                      'Units' , 'pixels'                                              , ...
                                      'Visible' , 'on'                                                , ...
                                      'BackgroundColor' , pale_green                                  , ...
                                      'ForegroundColor' , black                                       , ...
                                      'FontUnits' , 'pixels'                                          , ...
                                      'FontSize' , 15                                                 , ...
                                      'Position' , [ 230 , panel_height_ref , 140 , standard_height ]   ...                                        
                                    );
                                                
            start_time_2 = uicontrol( 'String' , ''                                                     , ...
                                      'Parent' , PANEL_2                                                , ...
                                      'Style' , 'text'                                                  , ...
                                      'HorizontalAlignment' , 'center'                                  , ...
                                      'Units' , 'pixels'                                                , ...
                                      'Visible' , 'on'                                                  , ...
                                      'BackgroundColor' , pale_green                                    , ...
                                      'ForegroundColor' , black                                         , ...
                                      'FontUnits' , 'pixels'                                            , ...
                                      'FontSize' , 15                                                   , ...
                                      'Position' , [ 230 , panel_height_ref , 140 , standard_height ]   ...                                        
                                    );
                                      
            start_time_3 = uicontrol( 'String' , ''                                                   , ...
                                      'Parent' , PANEL_3                                              , ...
                                      'Style' , 'text'                                                , ...
                                      'HorizontalAlignment' , 'center'                                , ...
                                      'Units' , 'pixels'                                              , ...
                                      'Visible' , 'on'                                                , ...
                                      'BackgroundColor' , pale_green                                  , ...
                                      'ForegroundColor' , black                                       , ...
                                      'FontUnits' , 'pixels'                                          , ...
                                      'FontSize' , 15                                                 , ...
                                      'Position' , [ 230 , panel_height_ref , 140 , standard_height ]   ...                                        
                                    );
                                 
            start_time_4 = uicontrol( 'String' , ''                                                   , ...
                                      'Parent' , PANEL_4                                              , ...
                                      'Style' , 'text'                                                , ...
                                      'HorizontalAlignment' , 'center'                                , ...
                                      'Units' , 'pixels'                                              , ...
                                      'Visible' , 'on'                                                , ...
                                      'BackgroundColor' , pale_green                                  , ...
                                      'ForegroundColor' , black                                       , ...
                                      'FontUnits' , 'pixels'                                          , ...
                                      'FontSize' , 15                                                 , ...
                                      'Position' , [ 230 , panel_height_ref , 140 , standard_height ]   ...                                        
                                    );          
                                      
            start_time_5 = uicontrol( 'String' , ''                                                   , ...
                                      'Parent' , PANEL_5                                              , ...
                                      'Style' , 'text'                                                , ...
                                      'HorizontalAlignment' , 'center'                                , ...
                                      'Units' , 'pixels'                                              , ...
                                      'Visible' , 'on'                                                , ...
                                      'BackgroundColor' , pale_green                                  , ...
                                      'ForegroundColor' , black                                       , ...
                                      'FontUnits' , 'pixels'                                          , ...
                                      'FontSize' , 15                                                 , ...
                                      'Position' , [ 230 , panel_height_ref , 140 , standard_height ]   ...                                        
                                    ); 
     
            start_time_6 = uicontrol( 'String' , ''                                                   , ...
                                      'Parent' , PANEL_6                                              , ...
                                      'Style' , 'text'                                                , ...
                                      'HorizontalAlignment' , 'center'                                , ...
                                      'Units' , 'pixels'                                              , ...
                                      'Visible' , 'on'                                                , ...
                                      'BackgroundColor' , pale_green                                  , ...
                                      'ForegroundColor' , black                                       , ...
                                      'FontUnits' , 'pixels'                                          , ...
                                      'FontSize' , 15                                                 , ...
                                      'Position' , [ 230 , panel_height_ref , 140 , standard_height ]   ...                                        
                                    );


            
            end_time_1 = uicontrol( 'String' , ''                                                   , ...
                                    'Parent' , PANEL_1                                              , ...
                                    'Style' , 'text'                                                , ...
                                    'HorizontalAlignment' , 'center'                                , ...
                                    'Units' , 'pixels'                                              , ...
                                    'Visible' , 'on'                                                , ...
                                    'BackgroundColor' , pale_orange                                 , ...
                                    'ForegroundColor' , black                                       , ...
                                    'FontUnits' , 'pixels'                                          , ...
                                    'FontSize' , 15                                                 , ...
                                    'Position' , [ 400 , panel_height_ref , 140 , standard_height ]   ...                                        
                                  );
                                                                 
            end_time_2 = uicontrol( 'String' , ''                                                    , ...
                                     'Parent' , PANEL_2                                              , ...
                                     'Style' , 'text'                                                , ...
                                     'HorizontalAlignment' , 'center'                                , ...
                                     'Units' , 'pixels'                                              , ...
                                     'Visible' , 'on'                                                , ...
                                     'BackgroundColor' , pale_orange                                 , ...
                                     'ForegroundColor' , black                                       , ...
                                     'FontUnits' , 'pixels'                                          , ...
                                     'FontSize' , 15                                                 , ...
                                     'Position' , [ 400 , panel_height_ref , 140 , standard_height ]   ...                                        
                                   );
                                                                  
            end_time_3 = uicontrol( 'String' , ''                                                   , ...
                                    'Parent' , PANEL_3                                              , ...
                                    'Style' , 'text'                                                , ...
                                    'HorizontalAlignment' , 'center'                                , ...
                                    'Units' , 'pixels'                                              , ...
                                    'Visible' , 'on'                                                , ...
                                    'BackgroundColor' , pale_orange                                 , ...
                                    'ForegroundColor' , black                                       , ...
                                    'FontUnits' , 'pixels'                                          , ...
                                    'FontSize' , 15                                                 , ...
                                    'Position' , [ 400 , panel_height_ref , 140 , standard_height ]   ...                                        
                                  );
                                                                         
            end_time_4 = uicontrol( 'String' , ''                                                   , ...
                                    'Parent' , PANEL_4                                              , ...
                                    'Style' , 'text'                                                , ...
                                    'HorizontalAlignment' , 'center'                                , ...
                                    'Units' , 'pixels'                                              , ...
                                    'Visible' , 'on'                                                , ...
                                    'BackgroundColor' , pale_orange                                 , ...
                                    'ForegroundColor' , black                                       , ...
                                    'FontUnits' , 'pixels'                                          , ...
                                    'FontSize' , 15                                                 , ...
                                    'Position' , [ 400 , panel_height_ref , 140 , standard_height ]   ...                                        
                                  );
                                                                  
            end_time_5 = uicontrol( 'String' , ''                                                   , ...
                                    'Parent' , PANEL_5                                              , ...
                                    'Style' , 'text'                                                , ...
                                    'HorizontalAlignment' , 'center'                                , ...
                                    'Units' , 'pixels'                                              , ...
                                    'Visible' , 'on'                                                , ...
                                    'BackgroundColor' , pale_orange                                 , ...
                                    'ForegroundColor' , black                                       , ...
                                    'FontUnits' , 'pixels'                                          , ...
                                    'FontSize' , 15                                                 , ...
                                    'Position' , [ 400 , panel_height_ref , 140 , standard_height ]   ...                                        
                                  );        
                                                                  
            end_time_6 = uicontrol( 'String' , ''                                                   , ...
                                    'Parent' , PANEL_6                                              , ...
                                    'Style' , 'text'                                                , ...
                                    'HorizontalAlignment' , 'center'                                , ...
                                    'Units' , 'pixels'                                              , ...
                                    'Visible' , 'on'                                                , ...
                                    'BackgroundColor' , pale_orange                                 , ...
                                    'ForegroundColor' , black                                       , ...
                                    'FontUnits' , 'pixels'                                          , ...
                                    'FontSize' , 15                                                 , ...
                                    'Position' , [ 400 , panel_height_ref , 140 , standard_height ]   ...                                        
                                  );



            elapsed_time_1 = uicontrol( 'String' , ''                                                   , ...
                                        'Parent' , PANEL_1                                              , ...
                                        'Style' , 'text'                                                , ...
                                        'HorizontalAlignment' , 'center'                                , ...
                                        'Units' , 'pixels'                                              , ...
                                        'Visible' , 'on'                                                , ...
                                        'BackgroundColor' , pale_yellow                                 , ...
                                        'ForegroundColor' , black                                       , ...
                                        'FontUnits' , 'pixels'                                          , ...
                                        'FontSize' , 17                                                 , ...
                                        'Position' , [ 570 , panel_height_ref , 150 , standard_height ]   ...                                        
                                      );
                                    
            elapsed_time_2 = uicontrol( 'String' , ''                                                   , ...
                                        'Parent' , PANEL_2                                              , ...
                                        'Style' , 'text'                                                , ...
                                        'HorizontalAlignment' , 'center'                                , ...
                                        'Units' , 'pixels'                                              , ...
                                        'Visible' , 'on'                                                , ...
                                        'BackgroundColor' , pale_yellow                                 , ...
                                        'ForegroundColor' , black                                       , ...
                                        'FontUnits' , 'pixels'                                          , ...
                                        'FontSize' , 17                                                 , ...
                                        'Position' , [ 570 , panel_height_ref , 150 , standard_height ]   ...                                        
                                      ); 
                       
            elapsed_time_3 = uicontrol( 'String' , ''                                                   , ...
                                        'Parent' , PANEL_3                                              , ...
                                        'Style' , 'text'                                                , ...
                                        'HorizontalAlignment' , 'center'                                , ...
                                        'Units' , 'pixels'                                              , ...
                                        'Visible' , 'on'                                                , ...
                                        'BackgroundColor' , pale_yellow                                 , ...
                                        'ForegroundColor' , black                                       , ...
                                        'FontUnits' , 'pixels'                                          , ...
                                        'FontSize' , 17                                                 , ...
                                        'Position' , [ 570 , panel_height_ref , 150 , standard_height ]   ...                                        
                                      );
                                    
            elapsed_time_4 = uicontrol( 'String' , ''                                                   , ...
                                        'Parent' , PANEL_4                                              , ...
                                        'Style' , 'text'                                                , ...
                                        'HorizontalAlignment' , 'center'                                , ...
                                        'Units' , 'pixels'                                              , ...
                                        'Visible' , 'on'                                                , ...
                                        'BackgroundColor' , pale_yellow                                 , ...
                                        'ForegroundColor' , black                                       , ...
                                        'FontUnits' , 'pixels'                                          , ...
                                        'FontSize' , 17                                                 , ...
                                        'Position' , [ 570 , panel_height_ref , 150 , standard_height ]   ...                                        
                                      ); 
                                  
            elapsed_time_5 = uicontrol( 'String' , ''                                                   , ...
                                        'Parent' , PANEL_5                                              , ...
                                        'Style' , 'text'                                                , ...
                                        'HorizontalAlignment' , 'center'                                , ...
                                        'Units' , 'pixels'                                              , ...
                                        'Visible' , 'on'                                                , ...
                                        'BackgroundColor' , pale_yellow                                 , ...
                                        'ForegroundColor' , black                                       , ...
                                        'FontUnits' , 'pixels'                                          , ...
                                        'FontSize' , 17                                                 , ...
                                        'Position' , [ 570 , panel_height_ref , 150 , standard_height ]   ...                                        
                                      );
                      
            elapsed_time_6 = uicontrol( 'String' , ''                                                   , ...
                                        'Parent' , PANEL_6                                              , ...
                                        'Style' , 'text'                                                , ...
                                        'HorizontalAlignment' , 'center'                                , ...
                                        'Units' , 'pixels'                                              , ...
                                        'Visible' , 'on'                                                , ...
                                        'BackgroundColor' , pale_yellow                                 , ...
                                        'ForegroundColor' , black                                       , ...
                                        'FontUnits' , 'pixels'                                          , ...
                                        'FontSize' , 17                                                 , ...
                                        'Position' , [ 570 , panel_height_ref , 150 , standard_height ]   ...                                        
                                      );

              
                                       
            money_1 = uicontrol( 'String' , ''                                                                              , ...
                                 'Parent' , PANEL_1                                                                         , ...
                                 'Style' , 'text'                                                                           , ...
                                 'HorizontalAlignment' , 'center'                                                           , ...
                                 'Units' , 'pixels'                                                                         , ...
                                 'Visible' , 'on'                                                                           , ...
                                 'BackgroundColor' , pale_yellow                                                            , ...
                                 'ForegroundColor' , black                                                                  , ...
                                 'FontUnits' , 'pixels'                                                                     , ...
                                 'FontSize' , 17                                                                            , ...
                                 'Position' , [ 570 , panel_height_ref+standard_height+button_gap , 150 , standard_height ]   ...                                        
                               );
                 
            money_2 = uicontrol( 'String' , ''                                                                                , ...
                                   'Parent' , PANEL_2                                                                         , ...
                                   'Style' , 'text'                                                                           , ...
                                   'HorizontalAlignment' , 'center'                                                           , ...
                                   'Units' , 'pixels'                                                                         , ...
                                   'Visible' , 'on'                                                                           , ...
                                   'BackgroundColor' , pale_yellow                                                            , ...
                                   'ForegroundColor' , black                                                                  , ...
                                   'FontUnits' , 'pixels'                                                                     , ...
                                   'FontSize' , 17                                                                            , ...
                                   'Position' , [ 570 , panel_height_ref+standard_height+button_gap , 150 , standard_height ]   ...                                        
                                 );
                                                      
            money_3 = uicontrol( 'String' , ''                                                                                , ...
                                   'Parent' , PANEL_3                                                                         , ...
                                   'Style' , 'text'                                                                           , ...
                                   'HorizontalAlignment' , 'center'                                                           , ...
                                   'Units' , 'pixels'                                                                         , ...
                                   'Visible' , 'on'                                                                           , ...
                                   'BackgroundColor' , pale_yellow                                                            , ...
                                   'ForegroundColor' , black                                                                  , ...
                                   'FontUnits' , 'pixels'                                                                     , ...
                                   'FontSize' , 17                                                                            , ...
                                   'Position' , [ 570 , panel_height_ref+standard_height+button_gap , 150 , standard_height ]   ...                                        
                                 );
                                                                   
            money_4 = uicontrol( 'String' , ''                                                                                , ...
                                   'Parent' , PANEL_4                                                                         , ...
                                   'Style' , 'text'                                                                           , ...
                                   'HorizontalAlignment' , 'center'                                                           , ...
                                   'Units' , 'pixels'                                                                         , ...
                                   'Visible' , 'on'                                                                           , ...
                                   'BackgroundColor' , pale_yellow                                                            , ...
                                   'ForegroundColor' , black                                                                  , ...
                                   'FontUnits' , 'pixels'                                                                     , ...
                                   'FontSize' , 17                                                                            , ...
                                   'Position' , [ 570 , panel_height_ref+standard_height+button_gap , 150 , standard_height ]   ...                                        
                                 );
                                                                                                  
            money_5 = uicontrol( 'String' , ''                                                                                , ...
                                   'Parent' , PANEL_5                                                                         , ...
                                   'Style' , 'text'                                                                           , ...
                                   'HorizontalAlignment' , 'center'                                                           , ...
                                   'Units' , 'pixels'                                                                         , ...
                                   'Visible' , 'on'                                                                           , ...
                                   'BackgroundColor' , pale_yellow                                                            , ...
                                   'ForegroundColor' , black                                                                  , ...
                                   'FontUnits' , 'pixels'                                                                     , ...
                                   'FontSize' , 17                                                                            , ...
                                   'Position' , [ 570 , panel_height_ref+standard_height+button_gap , 150 , standard_height ]   ...                                        
                                 );
                                            
            money_6 = uicontrol( 'String' , ''                                                                                , ...
                                   'Parent' , PANEL_6                                                                         , ...
                                   'Style' , 'text'                                                                           , ...
                                   'HorizontalAlignment' , 'center'                                                           , ...
                                   'Units' , 'pixels'                                                                         , ...
                                   'Visible' , 'on'                                                                           , ...
                                   'BackgroundColor' , pale_yellow                                                            , ...
                                   'ForegroundColor' , black                                                                  , ...
                                   'FontUnits' , 'pixels'                                                                     , ...
                                   'FontSize' , 17                                                                            , ...
                                   'Position' , [ 570 , panel_height_ref+standard_height+button_gap , 150 , standard_height ]   ...                                        
                                 );
                             
                                    
    
    % dynamic text
    %++++++++++++++++++++++++++++++  end  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++      
    
    
    
    
    
    % input text
    % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    % $$$$$$$$$$$$$$$$$$$$$ beginning $$$$$$$$$$$$$$$$$$$$$$$$$$$
        
        input_1 = uicontrol( 'String' , ''                                                  , ...
                             'Parent' , PANEL_1                                             , ...
                             'Style' , 'edit'                                               , ...
                             'HorizontalAlignment' , 'center'                               , ...
                             'Units' , 'pixels'                                             , ...
                             'Visible' , 'on'                                               , ...
                             'Enable' , 'on'                                                , ...
                             'BackgroundColor' , pale_grey                                  , ... 
                             'ForegroundColor' , black                                      , ...
                             'FontUnits' , 'pixels'                                         , ...
                             'FontSize' , 18                                                , ...
                             'Position' , [ 30 , panel_height_ref , 170 , standard_height ]   ...                                        
                            );
                            
                               
       input_2 = uicontrol( 'String' , '' , ...
                            'Parent' , PANEL_2                                             , ...
                            'Style' , 'edit'                                               , ...
                            'HorizontalAlignment' , 'center'                               , ...
                            'Units' , 'pixels'                                             , ...
                            'Visible' , 'on'                                               , ...
                            'Enable' , 'on'                                                , ...
                            'BackgroundColor' , pale_grey                                  , ... 
                            'ForegroundColor' , black                                      , ...
                            'FontUnits' , 'pixels'                                         , ...
                            'FontSize' , 18                                                , ...
                            'Position' , [ 30 , panel_height_ref , 170 , standard_height ]   ...                                   
                          );
                                  
                                   
      input_3 = uicontrol( 'String' , ''                                                  , ...
                           'Parent' , PANEL_3                                             , ...
                           'Style' , 'edit'                                               , ...
                           'HorizontalAlignment' , 'center'                               , ...
                           'Units' , 'pixels'                                             , ...
                           'Visible' , 'on'                                               , ...
                           'Enable' , 'on'                                                , ...
                           'BackgroundColor' , pale_grey                                  , ... 
                           'ForegroundColor' , black                                      , ...
                           'FontUnits' , 'pixels'                                         , ...
                           'FontSize' , 18                                                , ...
                           'Position' , [ 30 , panel_height_ref , 170 , standard_height ]   ...
                         );     
             
                               
      input_4 = uicontrol( 'String' , ''                                                  , ...
                           'Parent' , PANEL_4                                             , ...
                           'Style' , 'edit'                                               , ...
                           'HorizontalAlignment' , 'center'                               , ...
                           'Units' , 'pixels'                                             , ...
                           'Visible' , 'on'                                               , ...
                           'Enable' , 'on'                                                , ...
                           'BackgroundColor' , pale_grey                                  , ... 
                           'ForegroundColor' , black                                      , ...
                           'FontUnits' , 'pixels'                                         , ...
                           'FontSize' , 18                                                , ...
                           'Position' , [ 30 , panel_height_ref , 170 , standard_height ]   ...                                        
                         );

                             
      input_5 = uicontrol( 'String' , ''                                                  , ...
                           'Parent' , PANEL_5                                             , ...
                           'Style' , 'edit'                                               , ...
                           'HorizontalAlignment' , 'center'                               , ...
                           'Units' , 'pixels'                                             , ...
                           'Visible' , 'on'                                               , ...
                           'Enable' , 'on'                                                , ...
                           'BackgroundColor' , pale_grey                                  , ... 
                           'ForegroundColor' , black                                      , ...
                           'FontUnits' , 'pixels'                                         , ...
                           'FontSize' , 18                                                , ...
                           'Position' , [ 30 , panel_height_ref , 170 , standard_height ]   ...
                         );     
             
                               
      input_6 = uicontrol( 'String' , ''                                                  , ...
                           'Parent' , PANEL_6                                             , ...
                           'Style' , 'edit'                                               , ...
                           'HorizontalAlignment' , 'center'                               , ...
                           'Units' , 'pixels'                                             , ...
                           'Visible' , 'on'                                               , ...
                           'Enable' , 'on'                                                , ...
                           'BackgroundColor' , pale_grey                                  , ... 
                           'ForegroundColor' , black                                      , ...
                           'FontUnits' , 'pixels'                                         , ...
                           'FontSize' , 18                                                , ...
                           'Position' , [ 30 , panel_height_ref , 170 , standard_height ]   ...                                        
                         );


                            
    % input text
    % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    % $$$$$$$$$$$$$$$$$$$$$$$$$ end $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                          
             
        
    
              data_list  = [ reset_1        , ... %1   button
                             reset_2        , ... %2   button
                             reset_3        , ... %3   button
                             reset_4        , ... %4   button
                             reset_5        , ... %5   button
                             reset_6        , ... %6   button
                             start_1        , ... %7   button
                             start_2        , ... %8   button
                             start_3        , ... %9   button
                             start_4        , ... %10  button
                             start_5        , ... %11  button
                             start_6        , ... %12  button
                             end_1          , ... %13  button
                             end_2          , ... %14 button
                             end_3          , ... %15 button
                             end_4          , ... %16 button
                             end_5          , ... %17 button
                             end_6          , ... %18 button
                             start_time_1   , ... %19 text
                             start_time_2   , ... %20 text
                             start_time_3   , ... %21 text
                             start_time_4   , ... %22 text
                             start_time_5   , ... %23 text
                             start_time_6   , ... %24 text
                             end_time_1     , ... %25 text
                             end_time_2     , ... %26 text
                             end_time_3     , ... %27 text
                             end_time_4     , ... %28 text
                             end_time_5     , ... %29 text
                             end_time_6     , ... %30 text
                             elapsed_time_1 , ... %31 text
                             elapsed_time_2 , ... %32 text
                             elapsed_time_3 , ... %33 text
                             elapsed_time_4 , ... %34 text
                             elapsed_time_5 , ... %35 text
                             elapsed_time_6 , ... %36 text
                             input_1        , ... %37 input text
                             input_2        , ... %38 input text
                             input_3        , ... %39 input text
                             input_4        , ... %40 input text
                             input_5        , ... %41 input text
                             input_6        , ... %42 input text
                             money_1        , ... %43 text
                             money_2        , ... %44 text
                             money_3        , ... %45 text
                             money_4        , ... %46 text
                             money_5        , ... %47 text
                             money_6        , ... %48 text
                             undo_button    , ... %49 button
                             exit_button      ... %50 button
                           ];
    
                           
              set( INTERNET_FIGURE , 'UserData' , data_list );
              set( INTERNET_FIGURE , 'Visible' , 'off' );
              
              set( INTERNET_FIGURE , 'CloseRequestFcn' , 'closereq' );
              set( INTERNET_FIGURE , 'Backingstore' , 'on' );
              
              watchoff( mouse_pointer );
    
output = INTERNET_FIGURE;
