 function output = shop_figure( title , function_name , shortcut_panel_1 , shortcut_panel_2 , other_buttons )
        
        mouse_pointer = watchon();
            
        % define colour
        grey = [ 0.5 , 0.5 , 0.5 ];
        white = [ 1 1 1 ];
        black = [ 0 0 0 ];
        blue = [ 0.1 0.15 1 ];
        orange = [ .9 0.4 0.2 ];
        
        pale_green =  [ 0.9 1 0.9];
        pale_orange = [ 1 1 .95 ];
        pale_yellow = [ .9 0.9 0.8 ];
        pale_grey = [ 0.9 0.9 0.9 ];
        
        
        screen_details = get(0,'ScreenSize');
        fig_x = 1000;
        fig_y = 660; 
            
    
        MAIN_FIGURE = figure( 'Name' , 'Shop Program' , ...
                              'Units', 'pixels',...
                              'resize', 'off', ...
                              'NumberTitle' , 'off' , ...
                              'Visible' , 'off' , ...
                              'position', [ 10 , abs( screen_details(4) - fig_y - 45 ) ,  fig_x , fig_y ] ...
                            );
             
                            
                        
        colordef( MAIN_FIGURE , 'black' );
        
        
        % panels  
        % &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        % &&&&&&&&&&&&&&&&&&&&&&&&& beginning &&&&&&&&&&&&&&&&&&&&&&&
            customer_panel = uipanel( 'Title' , title , ...
                                      'Parent' , MAIN_FIGURE , ...
                                      'FontName' , 'Arial' , ...
                                      'FontUnits' , 'points' , ...
                                      'FontWeight' , 'bold' , ...
                                      'FontSize' , 15 , ...
                                      'Units' , 'pixels' , ...
                                      'Visible' , 'on' , ...
                                      'BackgroundColor' , grey , ...
                                      'Position' , [ 20 , 470 , 650 , 170 ]  ...
                                    );  
                             
                              
            generate_total_panel = uipanel( 'Title' , 'Total Amount' , ...
                                            'Parent' , MAIN_FIGURE , ...
                                            'FontName' , 'Arial' , ...
                                            'FontUnits' , 'points' , ...
                                            'FontWeight' , 'bold' , ...
                                            'FontSize' , 15 , ...
                                            'Units' , 'pixels' , ...
                                            'Visible' , 'on' , ...
                                            'BackgroundColor' , grey , ...
                                            'Position' , [ 20 , 340 , 460 , 110 ]  ...
                                          );  
                                  
                              
            generate_change_panel = uipanel( 'Title' , 'Change' , ...
                                             'Parent' , MAIN_FIGURE , ...
                                             'FontName' , 'Arial' , ...
                                             'FontUnits' , 'points' , ...
                                             'FontWeight' , 'bold' , ...
                                             'FontSize' , 15 , ...
                                             'Units' , 'pixels' , ...
                                             'Visible' , 'on' , ...
                                             'BackgroundColor' , grey , ...
                                             'Position' , [ 20 , 140 , 460 , 180 ]  ...
                                           );  
                                       
                                   
            change_sub_panel = uipanel( 'Parent' , MAIN_FIGURE , ...
                                        'Units' , 'pixels' , ...
                                        'Visible' , 'on' , ...
                                        'BackgroundColor' , grey , ...
                                        'Position' , [ 40 , 160 , 180 , 50 ]  ...
                                      );   
                                  
                                      
           show_cust_panel = uipanel( 'Title' , 'Customer View' , ...
                                      'Parent' , MAIN_FIGURE , ...
                                      'FontName' , 'Arial' , ...
                                      'FontUnits' , 'points' , ...
                                      'FontWeight' , 'bold' , ...
                                      'FontSize' , 15 , ...
                                      'Units' , 'pixels' , ...
                                      'Visible' , 'on' , ...
                                      'BackgroundColor' , grey , ...
                                      'Position' , [ 700 , 20 , 280 , 620 ]  ...
                                     );  
                                  
                                      
           shortcut_1_panel = uipanel( 'Parent' , MAIN_FIGURE , ...
                                       'Units' , 'pixels' , ...
                                       'Visible' , 'on' , ...
                                       'BackgroundColor' , grey , ...
                                       'Position' , [ 20 , 20 , 460 , 100 ]  ...
                                     ); 
                                       
                                      
           shortcut_2_panel = uipanel( 'Parent' , MAIN_FIGURE , ...
                                       'Units' , 'pixels' , ...
                                       'Visible' , 'on' , ...
                                       'BackgroundColor' , grey , ...
                                       'Position' , [ 500 , 140 , 170 , 310 ]  ...
                                     ); 
                                     
                                                
           task_panel = uipanel( 'Parent' , MAIN_FIGURE , ...
                                 'Units' , 'pixels' , ...
                                 'Visible' , 'on' , ...
                                 'BackgroundColor' , grey , ...
                                 'Position' , [ 500 , 20 , 170 , 100 ]  ...
                               ); 
                                                
                                  
                                       
        % panels                      
        % &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        % &&&&&&&&&&&&&&&&&&&&&&&&& end &&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        
        
        
        
        % buttons
        % ###########################################################
        % ####################### beginning #########################
                                           
            % "customer" button      
            callbr = callname( function_name , char(other_buttons(1,1)) ); 
            NEW_CUSTOMER_BUTTON = uicontrol( 'String' , char(other_buttons(1,1))  , ...
                                             'Parent' , customer_panel , ...
                                             'Style' , 'pushbutton' , ...
                                             'HorizontalAlignment' , 'center' , ...
                                             'Units' , 'pixels' , ...
                                             'Visible' , 'off' , ...
                                             'Interruptible' , 'off' , ...
                                             'Callback' , callbr , ...
                                             'Position' , [ 20 , 20 , 180 , 120 ] , ...
                                             'HorizontalAlignment' , 'center' , ...
                                             'FontUnits' , 'pixels' , ...
                                             'FontSize' , 19 ...
                                           ); 
           
                                        
            % "generate the total amount" button
            callbr = callname( function_name , char(other_buttons(1,2)) ); 
            GENERATE_TOTAL_BUTTON = uicontrol( 'String' , char(other_buttons(1,2)) , ...
                                               'Parent' , generate_total_panel , ...
                                               'Style' , 'pushbutton' , ...
                                               'HorizontalAlignment' , 'center' , ...
                                               'Units' , 'pixels' , ...
                                               'Visible' , 'off' , ...
                                               'Interruptible' , 'off' , ...
                                               'Callback' , callbr , ...
                                               'FontUnits' , 'pixels' , ...
                                               'FontSize' , 15 ,...
                                               'FontWeight' , 'bold' , ...
                                               'Position' , [ 20 , 20 , 180 , 60 ] ...
                                             );  
            
                                             
            % generate change button
            callbr = callname( function_name , char(other_buttons(1,3)) ); 
            GENERATE_CHANGE_BUTTON = uicontrol( 'String' , char(other_buttons(1,3)) , ...
                                                'Parent' , change_sub_panel , ...
                                                'Style' , 'pushbutton' , ...
                                                'HorizontalAlignment' , 'center' , ...
                                                'Units' , 'pixels' , ...
                                                'Visible' , 'off' , ...
                                                'Interruptible' , 'off' , ...
                                                'Callback' , callbr , ...
                                                'Position' , [ 1 , 1 , 180 , 50 ] , ...
                                                'FontUnits' , 'pixels' , ...
                                                'FontWeight' , 'bold' , ...
                                                'FontSize' , 15 ...
                                             );  
                                           
             
             % "Record button    
             callbr = callname( function_name , char(other_buttons(1,4)) ); 
             RECORD_BUTTON = uicontrol( 'String' , char(other_buttons(1,4)) , ...
                                        'Parent' , task_panel , ...
                                        'Style' , 'pushbutton' , ...
                                        'HorizontalAlignment' , 'center' , ...
                                        'Units' , 'pixels' , ...
                                        'Visible' , 'on' , ...
                                        'Interruptible' , 'off' , ...
                                        'Callback' , callbr , ...
                                        'FontUnits' , 'pixels' , ...
                                        'FontSize' , 13 , ...
                                        'FontWeight' , 'bold' , ...
                                        'Position' , [ 12  , 55 , 68 , 34 ]  ...
                                      );                          
                                               
                                      
                                      
             % "Print" button      
             callbr = callname( function_name , char(other_buttons(1,5)) ); 
             PRINT_BUTTON  = uicontrol( 'String' , char(other_buttons(1,5)) , ...
                                       'Parent' , task_panel , ...
                                       'Style' , 'pushbutton' , ...
                                       'HorizontalAlignment' , 'center' , ...
                                       'Units' , 'pixels' , ...
                                       'Visible' , 'off' , ...
                                       'Interruptible' , 'off' , ...
                                       'Callback' , callbr , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontSize' , 13 , ...
                                       'FontWeight' , 'bold' , ...
                                       'Position' , [ 94  , 55 , 68 , 34 ]  ...
                                      );  
                                  
                                      
             % "Exit" button
             callbr = callname( function_name , char(other_buttons(1,6)) ); 
             EXIT_BUTTON = uicontrol( 'String' , char(other_buttons(1,6)) , ...
                                      'Parent' , task_panel , ...
                                      'Style' , 'pushbutton' , ...
                                      'HorizontalAlignment' , 'center' , ...
                                      'Units' , 'pixels' , ...
                                      'Visible' , 'off' , ...
                                      'Interruptible' , 'off' , ...
                                      'Callback' , callbr , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontWeight' , 'bold' , ...
                                      'FontSize' , 16 , ...
                                      'Position' , [ 12 , 13 , 150 , 34 ]  ...
                                     );
                                      
            %scroll up button   
            callbr = callname( function_name , char(other_buttons(1,7)) );              
            UP_BUTTON = uicontrol( 'String' , char(other_buttons(1,7)) , ...
                                   'Parent' , show_cust_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'off' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontWeight' , 'bold' , ...
                                   'FontSize' , 11 , ...
                                   'Position' , [ 18 , 43 , 244 , 20 ]  ...
                                 );
             

            %scroll down button
            callbr = callname( function_name , char(other_buttons(1,8)) );
            DOWN_BUTTON = uicontrol( 'String' , char(other_buttons(1,8)) , ...
                                     'Parent' , show_cust_panel , ...
                                     'Style' , 'pushbutton' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'Visible' , 'off' , ...
                                     'Interruptible' , 'off' , ...
                                     'Callback' , callbr , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontWeight' , 'bold' , ...
                                     'FontSize' , 11 , ...
                                     'Position' , [ 18 , 13 , 244 , 20 ]  ...
                                   );


      
                                     
            callbr = callname( function_name , char(shortcut_panel_1(1,1)) );                           
            BUTTON_11 = uicontrol( 'String' , char(shortcut_panel_1(1,1)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 18 , 55 , 98 , 34 ] ...
                                 );
                                           
                                          
                                         
                                         
            callbr = callname( function_name , char(shortcut_panel_1(1,2)) );                                 
            BUTTON_12 = uicontrol( 'String' , char(shortcut_panel_1(1,2)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...                                    
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 18 , 13 , 98 , 34 ] ...
                                 );                        
                                         
                                       
                                        
            callbr = callname( function_name , char(shortcut_panel_1(1,3)) );                             
            BUTTON_13 = uicontrol( 'String' , char(shortcut_panel_1(1,3)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 128 , 55 , 98 , 34 ] ...
                                 );
                                     
                             
            callbr = callname( function_name , char(shortcut_panel_1(1,4)) );                           
            BUTTON_14 = uicontrol( 'String' , char(shortcut_panel_1(1,4)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...                                        'FontSize' , 12 , ...
                                   'Position' , [ 128 , 13 , 98 , 34 ] ...
                                 );           
                                      
                   
        
        
        
            callbr = callname( function_name , char(shortcut_panel_1(1,5)) );                            
            BUTTON_15 = uicontrol( 'String' , char(shortcut_panel_1(1,5)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 238 , 55 , 98 , 34 ] ...
                                 );
           
                                         
                                           
                                           
                                           
            callbr = callname( function_name , char(shortcut_panel_1(1,6)) );                                 
            BUTTON_16 = uicontrol( 'String' , char(shortcut_panel_1(1,6)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 238 , 13 , 98 , 34 ] ...
                                 );                        
                                          
                                    
            
            callbr = callname( function_name , char(shortcut_panel_1(1,7)) );  
            BUTTON_17 = uicontrol( 'String' , char(shortcut_panel_1(1,7)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontWeight' , 'bold' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 348 , 55 , 98 , 34 ] ...
                                 );
                                     
                                        
                                        
            callbr = callname( function_name , char(shortcut_panel_1(1,8)) );                           
            BUTTON_18 = uicontrol( 'String' , char(shortcut_panel_1(1,8)) , ...
                                   'Parent' , shortcut_1_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontWeight' , 'bold' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 348 , 13 , 98 , 34 ] ...
                                 );           
                                             
                                      
             
                                         
            callbr = callname( function_name , char(shortcut_panel_2(1,1)) );                            
            BUTTON_21 = uicontrol( 'String' , char(shortcut_panel_2(1,1)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 12 , 266 , 150 , 32 ] ...
                                 );     
                
                                    
            callbr = callname( function_name , char(shortcut_panel_2(1,2)) );                      
            BUTTON_22 = uicontrol( 'String' , char(shortcut_panel_2(1,2)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr  , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 12 , 221 , 72 , 36 ] ...
                                 );    
                               
                                  
            callbr = callname( function_name , char(shortcut_panel_2(1,3)) );                           
            BUTTON_23 = uicontrol( 'String' , char(shortcut_panel_2(1,3)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr  , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 12 , ...
                                   'Position' , [ 90 , 221 , 72 , 36 ] ...
                                 );    
                               
                                                         
                                         
                                         
            callbr = callname( function_name , char(shortcut_panel_2(1,4)) );                        
            BUTTON_24 = uicontrol( 'String' , char(shortcut_panel_2(1,4)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 12 , 177 , 72 , 34 ] ...
                                 );    
                                        
                                    
            callbr = callname( function_name , char(shortcut_panel_2(1,5)) );                       
            BUTTON_25 = uicontrol( 'String' , char(shortcut_panel_2(1,5)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 90 , 177 , 72 , 34 ] ...
                                 );    
                 
                                       
            callbr = callname( function_name , char(shortcut_panel_2(1,6)) );                       
            BUTTON_26 = uicontrol( 'String' , char(shortcut_panel_2(1,6)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 12 , 145 , 150 , 27 ] ...
                                 );    
            
                                    
            callbr = callname( function_name , char(shortcut_panel_2(1,7)) );                         
            BUTTON_27 = uicontrol( 'String' , char(shortcut_panel_2(1,7)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 11 , ...
                                   'Position' , [ 12 , 101 , 72 , 34 ] ...
                                 );
           
                                          
            callbr = callname( function_name , char(shortcut_panel_2(1,8)) );                               
            BUTTON_28 = uicontrol( 'String' , char(shortcut_panel_2(1,8)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 11 , ...
                                   'Position' , [ 90 , 101 , 72 , 34 ]  ...
                                );                        
                                          
           
                                
            callbr = callname( function_name , char(shortcut_panel_2(1,9)) );                           
            BUTTON_29 = uicontrol( 'String' , char(shortcut_panel_2(1,9)) , ...
                                   'Parent' , shortcut_2_panel , ...
                                   'Style' , 'pushbutton' , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'off' , ...
                                   'Interruptible' , 'on' , ...
                                   'Callback' , callbr , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontWeight' , 'bold' , ...
                                   'FontSize' , 13 , ...
                                   'Position' , [ 12 , 57 , 72 , 34 ] ...
                                 );
                                     
                             
                                     
            callbr = callname( function_name , char(shortcut_panel_2(1,10)) );                         
            BUTTON_210 = uicontrol( 'String' , char(shortcut_panel_2(1,10)) , ...
                                    'Parent' , shortcut_2_panel , ...
                                    'Style' , 'pushbutton' , ...
                                    'HorizontalAlignment' , 'center' , ...
                                    'Units' , 'pixels' , ...
                                    'Visible' , 'off' , ...
                                    'Interruptible' , 'on' , ...
                                    'Callback' , callbr , ...
                                    'FontUnits' , 'pixels' , ...
                                    'FontWeight' , 'bold' , ...
                                    'FontSize' , 13 , ...
                                    'Position' , [ 90 , 57 , 72 , 34 ] ...
                                  ); 
                                         
                              
                                            
            callbr = callname( function_name , char(shortcut_panel_2(1,11)) );                         
            BUTTON_211 = uicontrol( 'String' , char(shortcut_panel_2(1,11)) , ...
                                       'Parent' , shortcut_2_panel , ...
                                       'Style' , 'pushbutton' , ...
                                       'HorizontalAlignment' , 'center' , ...
                                       'Units' , 'pixels' , ...
                                       'Visible' , 'off' , ...
                                       'Interruptible' , 'on' , ...
                                       'Callback' , callbr , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontWeight' , 'bold' , ...
                                       'FontSize' , 13 , ...
                                       'Position' , [ 12 , 12 , 150 , 35 ] ...
                                     );    
                                 
                                     
                                      
                                      
        % buttons
        % ###########################################################
        % ########################## end ############################                   
             
        
        
        
        
        
        % input text
        % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        % $$$$$$$$$$$$$$$$$$$$$ beginning $$$$$$$$$$$$$$$$$$$$$$$$$$$
            
            cust_text_1 = uicontrol( 'String' , '' , ...
                                     'Parent' , customer_panel , ...
                                     'Style' , 'edit' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , pale_grey , ...
                                     'Visible' , 'off' , ...
                                     'Tag' , 'input' , ...
                                     'FontName' , 'Courier New' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 25 , ...
                                     'Position' , [ 220 , 105 , 125 , 35 ] ...                                        
                                   );
                               
                                   
            cust_text_2 = uicontrol( 'String' , '' , ...
                                     'Parent' , customer_panel , ...
                                     'Style' , 'edit' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , pale_grey , ...
                                     'Visible' , 'off' , ...
                                     'Tag' , 'input' , ...
                                     'FontName' , 'Courier New' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 25 , ...
                                     'Position' , [ 360 , 105 , 125 , 35 ] ...                                        
                                   );                       
                                   
                                   
            cust_text_3 = uicontrol( 'String' , '' , ...
                                     'Parent' , customer_panel , ...
                                     'Style' , 'edit' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , pale_grey , ...
                                     'Visible' , 'off' , ...
                                     'Tag' , 'input' , ...
                                     'FontName' , 'Courier New' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 25 , ...
                                     'Position' , [ 500 , 105 , 125 , 35 ] ...                                        
                                   );                  
                                  
                                   
            cust_text_4 = uicontrol( 'String' , '' , ...
                                     'Parent' , customer_panel , ...
                                     'Style' , 'edit' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , pale_grey , ...
                                     'Visible' , 'off' , ...
                                     'Tag' , 'input' , ...
                                     'FontName' , 'Courier New' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 25 , ...
                                     'Position' , [ 220 , 63 , 125 , 35 ] ...                                        
                                   );
                                   
                                   
            cust_text_5 = uicontrol( 'String' , '' , ...
                                     'Parent' , customer_panel , ...
                                     'Style' , 'edit' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , pale_grey , ...
                                     'Visible' , 'off' , ...
                                     'Tag' , 'input' , ...
                                     'FontName' , 'Courier New' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 25 , ...
                                     'Position' , [ 360 , 63 , 125 , 35 ] ...                                        
                                   );     
                                   
                                   
            cust_text_6 = uicontrol( 'String' , '' , ...
                                     'Parent' , customer_panel , ...
                                     'Style' , 'edit' , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , pale_grey , ...
                                     'Visible' , 'off' , ...
                                     'Tag' , 'input' , ...
                                     'FontName' , 'Courier New' , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 25 , ...
                                     'Position' , [ 500 , 63 , 125 , 35 ] ...                                        
                                   );
            
                                   
            cust_text_extra_1 = uicontrol( 'String' , '' , ...
                                           'Parent' , customer_panel , ...
                                           'Style' , 'edit' , ...
                                           'HorizontalAlignment' , 'center' , ...
                                           'Units' , 'pixels' , ...
                                           'BackgroundColor' , pale_yellow , ...
                                           'Visible' , 'off' , ...
                                           'Tag' , 'input' , ...
                                           'FontName' , 'Helvetica' , ...
                                           'FontUnits' , 'pixels' , ...
                                           'FontSize' , 22 , ...
                                           'Position' , [ 220 , 20 , 125 , 35 ] ...                                        
                                         );  
                                             
                                         
            cust_text_extra_2 = uicontrol( 'String' , '' , ...
                                           'Parent' , customer_panel , ...
                                           'Style' , 'edit' , ...
                                           'HorizontalAlignment' , 'center' , ...
                                           'Units' , 'pixels' , ...
                                           'BackgroundColor' , pale_yellow , ...
                                           'Visible' , 'off' , ...
                                           'Tag' , 'input' , ...
                                           'FontName' , 'Helvetica' , ...
                                           'FontUnits' , 'pixels' , ...
                                           'FontSize' , 22 , ...
                                           'Position' , [ 360 , 20 , 125 , 35 ] ...                                        
                                         );   
                                     
                                  
            cust_text_extra_3 = uicontrol( 'String' , '' , ...
                                           'Parent' , customer_panel , ...
                                           'Style' , 'edit' , ...
                                           'HorizontalAlignment' , 'center' , ...
                                           'Units' , 'pixels' , ...
                                           'BackgroundColor' , pale_yellow , ...
                                           'Visible' , 'off' , ...
                                           'Tag' , 'input' , ...
                                           'FontName' , 'Helvetica' , ...
                                           'FontUnits' , 'pixels' , ...
                                           'FontSize' , 22 , ...
                                           'Position' , [ 500 , 20 , 125 , 35 ] ...                                        
                                         );   
                                     
                                         
            input_money_text = uicontrol( 'String' , '' , ...
                                          'Parent' , generate_change_panel , ...
                                          'Style' , 'edit' , ...
                                          'HorizontalAlignment' , 'center' , ...
                                          'Units' , 'pixels' , ...
                                          'BackgroundColor' , 'white' , ...
                                          'Visible' , 'off' , ...
                                          'Tag' , 'input' , ...
                                          'FontName' , 'Tahoma' , ...
                                          'FontUnits' , 'pixels' , ...
                                          'FontSize' , 50 , ...
                                          'Position' , [ 20 , 85 , 180 , 65 ] ...
                                        ); 
        % input text
        % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        % $$$$$$$$$$$$$$$$$$$$$$$$$ end $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                          
             
        
        
        
        % static text
        % @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        % @@@@@@@@@@@@@@@@@@@@@@@@@ beginning @@@@@@@@@@@@@@@@@@@@@@@
        
            display_total_amount = uicontrol( 'Parent' , generate_total_panel , ...
                                              'Style' , 'text' , ...
                                              'Units' , 'pixels' , ...
                                              'BackgroundColor' ,pale_orange  , ...
                                              'ForegroundColor' , orange , ...
                                              'Visible' , 'off' , ...
                                              'Tag' , 'input' , ...
                                              'HorizontalAlignment' , 'center' , ...
                                              'FontName' , 'Tahoma' , ...
                                              'FontUnits' , 'pixels' , ...
                                              'FontSize' , 50 , ...
                                              'Position' , [ 225 , 15 , 210 , 70 ] ...                                        
                                            );
        
            display_change = uicontrol( 'Parent' , generate_change_panel , ...
                                        'Style' , 'text' , ...
                                        'Units' , 'pixels' , ...
                                        'BackgroundColor' , pale_green , ...
                                        'ForegroundColor' , blue , ...
                                        'Visible' , 'off' , ...
                                        'Tag' , 'input' , ...
                                        'HorizontalAlignment' , 'center' , ...
                                        'FontName' , 'Tahoma' , ...
                                        'FontUnits' , 'pixels' , ...
                                        'FontSize' , 50 , ...
                                        'Position' , [ 225 , 15 , 210 , 140 ] ...                                        
                                      );
                                           
                       
                                      
           % --------------------------------------                         
                                   
             display_1 = uicontrol( 'String' , '' , ...
                                    'Parent' , show_cust_panel , ...
                                    'Style' , 'text' , ...
                                    'Units' , 'pixels' , ...
                                    'BackgroundColor' , grey , ...
                                    'ForegroundColor' , black , ...
                                    'Visible' , 'on' , ...
                                    'HorizontalAlignment' , 'left' , ...
                                    'FontName' , 'Courier New' , ...
                                    'FontUnits' , 'pixels' , ...
                                    'FontSize' , 11 , ...
                                    'Position' , [ 20 , 559 , 240 , 24 ] ...                                        
                                  );
                               
                                   
                                   
           display_2 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 527 , 240 , 24 ] ...                                        
                                );
                               
           
           display_3 = uicontrol(  'String' , '' , ...
                                   'Parent' , show_cust_panel , ...
                                   'Style' , 'text' , ...
                                   'Units' , 'pixels' , ...
                                   'BackgroundColor' , grey , ...
                                   'ForegroundColor' , black , ...
                                   'Visible' , 'on' , ...
                                   'HorizontalAlignment' , 'left' , ...
                                   'FontName' , 'Courier New' , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontSize' , 11 , ...
                                   'Position' , [ 20 , 495 , 240 , 24 ] ...                                        
                               );
                               
           
           display_4 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 463 , 240 , 24 ] ...                                        
                                );
                               
           
           display_5 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 431 , 240 , 24 ] ...                                        
                                );
                               
           
           display_6 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 399 , 240 , 24 ] ...                                        
                                );
                               
           
           display_7 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 367 , 240 , 24 ] ...                                        
                                );
                               
           
           display_8 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 335 , 240 , 24 ] ...                                        
                                );
                               
                                   
          display_9 = uicontrol( 'String' , '' , ...
                                 'Parent' , show_cust_panel , ...
                                 'Style' , 'text' , ...
                                 'Units' , 'pixels' , ...
                                 'BackgroundColor' , grey , ...
                                 'ForegroundColor' , black , ...
                                 'Visible' , 'on' , ...
                                 'HorizontalAlignment' , 'left' , ...
                                 'FontName' , 'Courier New' , ...
                                 'FontUnits' , 'pixels' , ...
                                 'FontSize' , 11 , ...
                                 'Position' , [ 20 , 303 , 240 , 24 ] ...                                        
                               );
           
                                    
                                    
          display_10 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 11 , ...
                                  'Position' , [ 20 , 271 , 240 , 24 ] ...                                        
                                );
                                    

                                   
          display_11 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text', ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 10 , ...
                                  'Position' , [ 20 , 239 , 240 , 24 ] ...                                        
                                );
                           
                                
                 
          display_12 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text', ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 10 , ...
                                  'Position' , [ 20 , 207 , 240 , 24 ] ...                                        
                                );
                           
                                

          display_13 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text', ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 10 , ...
                                  'Position' , [ 20 , 175 , 240 , 24 ] ...                                        
                                );
                           
                                
                                   
          display_14 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text', ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 10 , ...
                                  'Position' , [ 20 , 143 , 240 , 24 ] ...                                        
                                );
                           
                                

                                   
          display_15 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text', ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 10 , ...
                                  'Position' , [ 20 , 111 , 240 , 24 ] ...                                        
                                );
                           
                                
                 
                                   
          display_16 = uicontrol( 'String' , '' , ...
                                  'Parent' , show_cust_panel , ...
                                  'Style' , 'text', ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , grey , ...
                                  'ForegroundColor' , black , ...
                                  'Visible' , 'on' , ...
                                  'HorizontalAlignment' , 'left' , ...
                                  'FontName' , 'Courier New' , ...
                                  'FontUnits' , 'pixels' , ...
                                  'FontSize' , 10 , ...
                                  'Position' , [ 20 , 79 , 240 , 24 ] ...                                        
                                );
                           
                                


                                              
        % static text
        % @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        % @@@@@@@@@@@@@@@@@@@@@@@@@@@@ end @@@@@@@@@@@@@@@@@@@@@@@@@@
                             
                             
              % list of buttons
              data_list  = [ NEW_CUSTOMER_BUTTON    , ...                                           % 1
                             GENERATE_TOTAL_BUTTON  , ...                                           % 2
                             GENERATE_CHANGE_BUTTON , ...                                           % 3
                             RECORD_BUTTON          , ...                                           % 4
                             PRINT_BUTTON           , ...                                           % 5
                             BUTTON_21              , ...                                           % 6
                             BUTTON_22              , BUTTON_23          , ...                      % 7  , 8
                             BUTTON_24              , BUTTON_25          , BUTTON_26         , ...  % 9  , 10 , 11
                             BUTTON_27              , BUTTON_28          , ...                      % 12 , 13
                             BUTTON_29              , BUTTON_210         , ...                      % 14 , 15
                             BUTTON_211             , ...                                           % 16
                             BUTTON_11              , BUTTON_12          , ...                      % 17 , 18
                             BUTTON_13              , BUTTON_14          , ...                      % 19 , 20
                             BUTTON_15              , BUTTON_16          , ...                      % 21 , 22
                             BUTTON_17              , BUTTON_18          , ...                      % 23 , 24
                             UP_BUTTON              , DOWN_BUTTON        , ...                      % 25 , 26                                            % 57
                             cust_text_1            , cust_text_2        , cust_text_3       , ...  % 27 , 28 , 29 
                             cust_text_4            , cust_text_5        , cust_text_6       , ...  % 30 , 31 , 32
                             cust_text_extra_1      , cust_text_extra_2  , cust_text_extra_3 , ...  % 33 , 34 , 35
                             display_total_amount   , input_money_text   , display_change    , ...  % 36 , 37 , 38
                             display_1              , display_2          , display_3         , ...  % 39 , 40 , 41
                             display_4              , display_5          , display_6         , ...  % 42 , 43 , 44
                             display_7              , display_8          , display_9         , ...  % 45 , 46 , 47
                             display_10             , display_11         , display_12        , ...  % 48 , 49 , 50
                             display_13             , display_14         , display_15        , ...  % 51 , 52 , 53
                             display_16             , ...                                           % 54 
                             EXIT_BUTTON              ...                                           % 55
                             
                           ];                                                                           
                    
              set( MAIN_FIGURE , 'UserData' , data_list );
              set( data_list , 'Visible' , 'on' );
              set( data_list , 'Enable' , 'on' );
              
              set( MAIN_FIGURE , 'CloseRequestFcn' , 'closereq' );
              set( MAIN_FIGURE , 'Backingstore' , 'on' );
              set( MAIN_FIGURE , 'Visible' , 'on' );
              
              watchoff( mouse_pointer );
              

output = MAIN_FIGURE;

