% precondition: input_button_name is a string array of size 19
%              multi_trip_prices is an int array of size 8
%              single_trip_price is an int array of size 8
%              daytrip_price is an int array of size 3

function output = ticket( function_name , input_button_name , ticket_trip )

    mouse_pointer = watchon();
    
    format short g;
    gap_p = 30;
    small_gap = 5;
   
    
    %panel construction variables
    SCREEN_DETAILS = get(0,'ScreenSize');
    fig_x = 950;
    fig_y = 690;
    
    panel_length = 770;
    fare_panel_length = 770;
    
    
    daytrip_width = 90;
    single_width = 240;
    multi_width = 240;
    fare_width = 60;
    free_length = 120;
    title_width_type = 100;
    title_width = 42;
    title_width_daytrip = 50;
    
            
    text_length_type = 230;
    text_length_regular = 170;
    text_length_tertiary = 170;
    text_length_secondary = 185;
    
    TICKET_FIGURE = figure( 'Name' , 'Tickets' , ...
                            'Units', 'pixels',...
                            'resize', 'off', ...
                            'NumberTitle' , 'off' , ...
                            'Visible' , 'on' , ...
                            'position', [ 10 , abs( SCREEN_DETAILS(4) - fig_y - 45 ) ,  fig_x , fig_y ] ...
                           );
                       
    colordef( TICKET_FIGURE  , 'black' );
    
    
    
    
    dark_blue = [ 0.1 0.2 0.6 ] ;
    med_blue = [ 0.1 0.35 1 ];
    light_blue = [ 0.4 0.6 1 ];
    grey = [ 0.5 0.5 0.5 ];
    red = [ 1 0.22 0 ];
    green =  [ 0 1 0.1 ];
    white = [ 1 1 1 ];
    black = [ 0 0 0 ];
    
    
    
    % panel
    %----------------------------  begin  ---------------------------------
    %----------------------------------------------------------------------
    DAYTRIP_PANEL = uipanel( 'Parent' , TICKET_FIGURE , ...
                             'FontName' , 'Arial' , ...
                             'FontUnits' , 'points' , ...
                             'FontWeight' , 'bold' , ...
                             'FontSize' , 15 , ...
                             'Units' , 'pixels' , ...
                             'Visible' , 'on' , ...
                             'BackgroundColor' , [ 1 , 1 , 1 ] , ...
                             'Position' , [ gap_p , gap_p , panel_length , daytrip_width ]  ...
                           );  
                       
                           
     SINGLE_PANEL = uipanel( 'Parent' , TICKET_FIGURE , ...
                             'FontName' , 'Arial' , ...
                             'FontUnits' , 'points' , ...
                             'FontWeight' , 'bold' , ...
                             'FontSize' , 15 , ...
                             'Units' , 'pixels' , ...
                             'Visible' , 'on' , ...
                             'BackgroundColor' , [ 1 , 1 ,  1 ] , ...
                             'Position' , [ gap_p , gap_p +  daytrip_width , panel_length , single_width ]  ...
                           );  
                       
                           
     MULTI_PANEL = uipanel( 'Parent' , TICKET_FIGURE , ...
                            'FontName' , 'Arial' , ...
                            'FontUnits' , 'points' , ...
                            'FontWeight' , 'bold' , ...
                            'FontSize' , 15 , ...
                            'Units' , 'pixels' , ...
                            'Visible' , 'on' , ...
                            'BackgroundColor' , [ 1 , 1 , 1 ] , ...
                            'Position' , [ gap_p , gap_p +  daytrip_width + single_width  , panel_length , multi_width ]  ...
                          );
                       
                           
     FARE_PANEL = uipanel( 'Parent' , TICKET_FIGURE , ...
                           'FontName' , 'Arial' , ...
                           'FontUnits' , 'points' , ...
                           'FontWeight' , 'bold' , ...
                           'FontSize' , 15 , ...
                           'Units' , 'pixels' , ...
                           'Visible' , 'on' , ...
                           'BackgroundColor' , [ 1 , 1 , 1 ] , ...
                           'Position' , [ gap_p , gap_p +  daytrip_width + single_width + multi_width , fare_panel_length , fare_width ]  ...
                         );  
                               
                         
     OK_PANEL = uipanel( 'Parent' , TICKET_FIGURE , ...
                         'FontName' , 'Arial' , ...
                         'FontUnits' , 'points' , ...
                         'FontWeight' , 'bold' , ...
                         'FontSize' , 15 , ...
                         'Units' , 'pixels' , ...
                         'Visible' , 'on' , ...
                         'BackgroundColor' ,  grey  , ...
                         'Position' , [ gap_p + panel_length , gap_p , free_length , daytrip_width + single_width + multi_width + fare_width  ]  ...
                       );  
                                                                         
                            
    
    % panel
    %----------------------------  end  ---------------------------------
    %----------------------------------------------------------------------                      
                           
                   
    
                   
    % colour background
    % ()()()()()()()()()()()()() begin ()()()()()()()()()()()()()()
    % ()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()
          
           
    fare_schedule_cover = uicontrol( 'Parent' , FARE_PANEL , ...
                                     'Style' , 'text' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , dark_blue  , ...
                                     'Visible' , 'on' , ...
                                     'Position' , [ 1 , 1 , text_length_type , fare_width ] ...                                        
                                    );
                          
          
    regular_cover = uicontrol( 'Parent' , FARE_PANEL , ...
                               'Style' , 'text' , ...
                               'Units' , 'pixels' , ...
                               'BackgroundColor' , green   , ...
                               'Visible' , 'on' , ...
                               'Position' , [ text_length_type + small_gap*1.3 , 1 , text_length_regular , fare_width ] ...                                        
                             );
                          
                            
          
    tertiary_cover = uicontrol( 'Parent' , FARE_PANEL , ...
                                'Style' , 'text' , ...
                                'Units' , 'pixels' , ...
                                'BackgroundColor' , green   , ...
                                'Visible' , 'on' , ...
                                'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 1 , text_length_tertiary , fare_width ] ...                                        
                              );
                          
          
    secondary_cover = uicontrol( 'Parent' , FARE_PANEL , ...
                                 'Style' , 'text' , ...
                                 'BackgroundColor' , green   , ...
                                 'Visible' , 'on' , ...
                                 'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 1 , text_length_secondary , fare_width ] ...                                        
                               );
                          
            
                      
                                                                                
     gray_cover_multi = uicontrol( 'Parent' , MULTI_PANEL  , ...
                                   'Style' , 'text' , ...
                                   'Units' , 'pixels' , ...
                                   'BackgroundColor' , grey  , ... 
                                   'Visible' , 'on' , ...
                                   'Position' , [ 1  , 1 ,  text_length_type ,  title_width_type  ] ...                                        
                                  );
                       
                            
                            
                                                                                
     red_cover_multi = uicontrol( 'Parent' , MULTI_PANEL  , ...
                                  'Style' , 'text' , ...
                                  'Units' , 'pixels' , ...
                                  'BackgroundColor' , red  , ... 
                                  'Visible' , 'on' , ...
                                  'Position' , [ 1 , 1+title_width_type  ,  text_length_type ,  title_width_type  ] ...                                        
                                 );
                      
                                                                                
     white_cover_multi = uicontrol( 'Parent' , MULTI_PANEL  , ...
                                    'Style' , 'text' , ...
                                    'Units' , 'pixels' , ...
                                    'BackgroundColor' , white  , ...
                                    'Visible' , 'on' , ...
                                    'Position' , [ 2  , 1+title_width_type*2 , panel_length ,  title_width ] ...                                        
                                   );                                       
                            
                                                 
                   
                                                                                
     light_blue_cover_multi = uicontrol( 'Parent' , SINGLE_PANEL  , ...
                                         'Style' , 'text' , ...
                                         'Units' , 'pixels' , ...
                                         'BackgroundColor' , light_blue   , ... 
                                         'Visible' , 'on' , ...
                                         'Position' , [ 1  , 1 ,  text_length_type ,  title_width_type  ] ...                                        
                                       );
                       
                            
                            
                                                                                
     dark_blue_cover_multi = uicontrol( 'Parent' , SINGLE_PANEL  , ...
                                        'Style' , 'text' , ...
                                        'Units' , 'pixels' , ...
                                        'BackgroundColor' , med_blue  , ... 
                                        'Visible' , 'on' , ...
                                        'Position' , [ 1 , 1+title_width_type  ,  text_length_type ,  title_width_type  ] ...                                        
                                      );
                      
                                                                                
     white_cover_single = uicontrol( 'Parent' , SINGLE_PANEL  , ...
                                     'Style' , 'text' , ...
                                     'Units' , 'pixels' , ...
                                     'BackgroundColor' , white  , ...
                                     'Visible' , 'on' , ...
                                     'Position' , [ 2  , 1+title_width_type*2 , panel_length ,  title_width ] ...                                        
                                    );  
                                
                                 
                            
                                                                                
     dark_blue_cover_daytrip = uicontrol( 'Parent' , DAYTRIP_PANEL  , ...
                                          'Style' , 'text' , ...
                                          'Units' , 'pixels' , ...
                                          'BackgroundColor' , med_blue   , ... 
                                          'Visible' , 'on' , ...
                                          'Position' , [ 1 , 10 ,  text_length_type ,  title_width_daytrip  ] ...                                        
                                        );
                      
                                                                                
     white_cover_daytrip = uicontrol( 'Parent' , DAYTRIP_PANEL  , ...
                                      'Style' , 'text' , ...
                                      'Units' , 'pixels' , ...
                                      'BackgroundColor' , white , ...
                                      'Visible' , 'on' , ...
                                      'Position' , [ 2  , 10+title_width_daytrip , panel_length ,  title_width-10 ] ...                                        
                                     );  
                                
                     
    
    
    % ()()()()()()()()()()()()() end ()()()()()()()()()()()()()()()
    % ()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()
    
    
    
    
    
    
    % buttons
    % ============================ begin ==================================
    % =====================================================================
 
      
            price = num2str( ticket_trip(1,1) , '%2.2f' );
            price = [ '$' , price ];                                   
            callbr = callname( function_name , char(input_button_name(1,1)) );                                    
            multi_regular_button = uicontrol( 'String' , price , ...
                                              'Parent' , MULTI_PANEL , ...
                                              'Style' , 'pushbutton' , ...
                                              'Callback' , callbr , ...
                                              'HorizontalAlignment' , 'center' , ...
                                              'Units' , 'pixels' , ...
                                              'Visible' , 'on' , ...
                                              'Interruptible' , 'on' , ...
                                              'BackgroundColor' , red  , ... 
                                              'ForegroundColor' , white  , ...
                                              'FontUnits' , 'pixels' , ...
                                              'FontSize' , 20 , ...
                                              'Position' , [ text_length_type + small_gap*1.3 , 2 + title_width_type + title_width_type/2 , text_length_regular , title_width_type/2 ] ...
                                             );
                                         
                                         
                                             
            price = num2str(  ticket_trip(1,2) , '%2.2f');
            price = [ '$' , price ];                                                      
            callbr = callname( function_name , char(input_button_name(1,2)) );                                                
            multi_tertiary_button = uicontrol( 'String' , price , ...
                                               'Parent' , MULTI_PANEL , ...
                                               'Style' , 'pushbutton'  , ...
                                               'Callback' , callbr , ...
                                               'HorizontalAlignment' , 'center' , ...
                                               'Units' , 'pixels' , ...
                                               'Visible' , 'on' , ...
                                               'BackgroundColor' , red  , ... 
                                               'ForegroundColor' , white  , ...
                                               'FontUnits' , 'pixels' , ...
                                               'FontSize' , 20 , ...
                                               'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 2 + title_width_type + title_width_type/2  , text_length_tertiary , title_width_type/2 ] ...
                                             );       
                      
                 
                                                          
            price = num2str(  ticket_trip(1,3) , '%2.2f');
            price = [ '$' , price ];  
            callbr = callname( function_name , char(input_button_name(1,3)) );                                                
            multi_secondary_button = uicontrol( 'String' , price , ...
                                                'Parent' , MULTI_PANEL , ...
                                                'Style' , 'pushbutton'  , ...
                                                'Callback' , callbr , ...
                                                'HorizontalAlignment' , 'center' , ...
                                                'Units' , 'pixels' , ...
                                                'Visible' , 'on' , ...
                                                'BackgroundColor' , red  , ... 
                                                'ForegroundColor' , white , ...
                                                'FontUnits' , 'pixels' , ...
                                                'FontSize' , 20 , ...
                                                'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 2 + title_width_type + title_width_type/2 , text_length_secondary , title_width_type/2 ] ...                                        
                                              );
                                                                    
                       
                 
                                             
            price = num2str(  ticket_trip(1,4) , '%2.2f');
            price = [ '$' , price ];                                 
            callbr = callname( function_name , char(input_button_name(1,4)) );                      
            multi_2_section_button = uicontrol( 'String' , price , ...
                                                'Parent' , MULTI_PANEL , ...
                                                'Style' , 'pushbutton' , ...
                                                'Callback' , callbr , ...
                                                'HorizontalAlignment' , 'center' , ...
                                                'Units' , 'pixels' , ...
                                                'Visible' , 'on' , ...
                                                'Interruptible' , 'on' , ...
                                                'BackgroundColor' , red  , ... 
                                                'ForegroundColor' , white  , ...
                                                'FontUnits' , 'pixels' , ...
                                                'FontSize' , 20 , ...
                                                'Position' , [ text_length_type + small_gap*1.3 , 1+title_width_type , text_length_regular , title_width_type/2 ] ...
                                               );
                                           
                      
                                               
                                               
            multi_NA_tertiary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                            'Parent' , MULTI_PANEL , ...
                                                            'Style' , 'text' , ...
                                                            'HorizontalAlignment' , 'center' , ...
                                                            'Units' , 'pixels' , ...
                                                            'Visible' , 'on' , ...
                                                            'BackgroundColor' , red  , ... 
                                                            'ForegroundColor' , white  , ...
                                                            'FontUnits' , 'pixels' , ...
                                                            'FontSize' , 15 , ...
                                                            'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 1+title_width_type , text_length_tertiary , title_width_type/2 ] ...
                                                           );
                                           
                               
                                           
                                             
                                             
            multi_NA_secondary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                             'Parent' , MULTI_PANEL , ...
                                                             'Style' , 'text'  , ...
                                                             'HorizontalAlignment' , 'center' , ...
                                                             'Units' , 'pixels' , ...
                                                             'Visible' , 'on' , ...
                                                             'BackgroundColor' , red  , ... 
                                                             'ForegroundColor' , white  , ...
                                                             'FontUnits' , 'pixels' , ...
                                                             'FontSize' , 15 , ...
                                                             'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 1 + title_width_type , text_length_secondary , title_width_type/2 ] ...
                                                            );
                    
                 
                 
            price = num2str(  ticket_trip(1,5) , '%2.2f' );
            price = [ '$' , price ];                                              
            callbr = callname( function_name , char(input_button_name(1,5)) );                                               
            multi_interpeak_regular_button = uicontrol( 'String' , price , ...
                                                        'Parent' , MULTI_PANEL , ...
                                                        'Style' , 'pushbutton' , ...
                                                        'Callback' , callbr , ...
                                                        'HorizontalAlignment' , 'center' , ...
                                                        'Units' , 'pixels' , ...
                                                        'Visible' , 'on' , ...
                                                        'Interruptible' , 'on' , ...
                                                        'BackgroundColor' , grey  , ... 
                                                        'ForegroundColor' , black  , ...
                                                        'Callback' , callbr  , ...
                                                        'FontUnits' , 'pixels' , ...
                                                        'FontSize' , 20 , ...
                                                        'Position' , [ text_length_type + small_gap*1.3 , 2 + title_width_type/2 , text_length_regular , title_width_type/2 ] ...
                                                       );
                                           
                        
                 
                                                    
            price = num2str(  ticket_trip(1,6) , '%2.2f');
            price = [ '$' , price ];                                                          
            callbr = callname( function_name , char(input_button_name(1,6)) );                                                         
            multi_interpeak_tertiary_button = uicontrol( 'String' , price , ...
                                                         'Parent' , MULTI_PANEL , ...
                                                         'Style' , 'pushbutton'  , ...
                                                         'Callback' , callbr , ...
                                                         'HorizontalAlignment' , 'center' , ...
                                                         'Units' , 'pixels' , ...
                                                         'Visible' , 'on' , ...
                                                         'BackgroundColor' , grey  , ... 
                                                         'ForegroundColor' , black  , ...
                                                         'FontUnits' , 'pixels' , ...
                                                         'FontSize' , 20 , ...
                                                         'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 2 + title_width_type/2  , text_length_tertiary , title_width_type/2 ] ...
                                                        );
                                           
                             
            price = num2str(  ticket_trip(1,7) , '%2.2f');
            price = [ '$' , price ];                                                         
            callbr = callname( function_name , char(input_button_name(1,7)) );                                                          
            multi_interpeak_secondary_button = uicontrol( 'String' , price , ...
                                                          'Parent' , MULTI_PANEL , ...
                                                          'Style' , 'pushbutton' , ...
                                                          'Callback' , callbr , ...
                                                          'HorizontalAlignment' , 'center' , ...
                                                          'Units' , 'pixels' , ...
                                                          'Visible' , 'on' , ...
                                                          'BackgroundColor' , grey  , ... 
                                                          'ForegroundColor' , black   , ...
                                                          'FontUnits' , 'pixels' , ...
                                                          'FontSize' , 20 , ...
                                                          'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 2 + title_width_type/2 , text_length_secondary , title_width_type/2 ] ...                                        
                                                         );
                                       
                                                        
                                                         
            price = num2str(  ticket_trip(1,8) , '%2.2f');
            price = [ '$' , price ];                                              
            callbr = callname( function_name , char(input_button_name(1,8)) );                                   
            multi_interpeak_2_section_button = uicontrol( 'String' , price , ...
                                                          'Parent' , MULTI_PANEL , ...
                                                          'Style' , 'pushbutton' , ...
                                                          'Callback' , callbr , ...
                                                          'HorizontalAlignment' , 'center' , ...
                                                          'Units' , 'pixels' , ...
                                                          'Visible' , 'on' , ...
                                                          'Interruptible' , 'on' , ...
                                                          'BackgroundColor' , grey  , ... 
                                                          'ForegroundColor' , black , ...
                                                          'Callback' , callbr , ...
                                                          'FontUnits' , 'pixels' , ...
                                                          'FontSize' , 20 , ...
                                                          'Position' , [ text_length_type + small_gap*1.3 , 1 , text_length_regular , title_width_type/2 ] ...
                                                         );
                                           
                                         
                                              
                                                       
            multi_interpeak_NA_tertiary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                                      'Parent' , MULTI_PANEL , ...
                                                                      'Style' , 'text'  , ...
                                                                      'HorizontalAlignment' , 'center' , ...
                                                                      'Units' , 'pixels' , ...
                                                                      'Visible' , 'on' , ...
                                                                      'BackgroundColor' , grey  , ... 
                                                                      'ForegroundColor' , black  , ...
                                                                      'FontUnits' , 'pixels' , ...
                                                                      'FontSize' , 15 , ...
                                                                      'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 1 , text_length_tertiary , title_width_type/2 ] ...
                                                                    );
                                                        
            multi_interpeak_NA_secondary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                                       'Parent' , MULTI_PANEL , ...
                                                                       'Style' , 'text'  , ...
                                                                       'HorizontalAlignment' , 'center' , ...
                                                                       'Units' , 'pixels' , ...
                                                                       'Visible' , 'on' , ...
                                                                       'BackgroundColor' , grey  , ... 
                                                                       'ForegroundColor' , black  , ...
                                                                       'FontUnits' , 'pixels' , ...
                                                                       'FontSize' , 15 , ...
                                                                       'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 1  , text_length_secondary , title_width_type/2 ] ...
                                                                      );
                                                                  
                                                   
                    
                  
                  
                  
                                      
            price = num2str( ticket_trip(1,9) , '%2.2f');
            price = [ '$' , price ];
            callbr = callname( function_name , char(input_button_name(1,9)) );                  
            single_regular_button = uicontrol( 'String' , price , ...
                                               'Parent' , SINGLE_PANEL , ...
                                               'Style' , 'pushbutton' , ...
                                               'Callback' , callbr , ...
                                               'HorizontalAlignment' , 'center' , ...
                                               'Units' , 'pixels' , ...
                                               'Visible' , 'on' , ...
                                               'Interruptible' , 'on' , ...
                                               'BackgroundColor' , med_blue  , ... 
                                               'ForegroundColor' , white   , ...
                                               'FontUnits' , 'pixels' , ...
                                               'FontSize' , 20 , ...
                                               'Position' , [ text_length_type + small_gap*1.3 , 2 + title_width_type + title_width_type/2 , text_length_regular , title_width_type/2 ] ...
                                              );
                           
                  
                  
                                              
            price = num2str( ticket_trip(1,10) , '%2.2f');
            price = [ '$' , price ];                                     
            callbr = callname( function_name , char(input_button_name(1,10)) );           
            single_tertiary_button = uicontrol( 'String' , price , ...
                                                'Parent' , SINGLE_PANEL , ...
                                                'Style' , 'pushbutton'  , ...
                                                'Callback' , callbr , ...
                                                'HorizontalAlignment' , 'center' , ...
                                                'Units' , 'pixels' , ...
                                                'Visible' , 'on' , ...
                                                'BackgroundColor' , med_blue  , ... 
                                                'ForegroundColor' , white   , ...
                                                'FontUnits' , 'pixels' , ...
                                                'FontSize' , 20 , ...
                                                'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 2 + title_width_type + title_width_type/2  , text_length_tertiary , title_width_type/2 ] ...
                                              );
                                           
                          
                  
                                              
            price = num2str( ticket_trip(1,11) , '%2.2f');
            price = [ '$' , price ];                                                       
            callbr = callname( function_name , char(input_button_name(1,11)) );                                                 
            single_secondary_button = uicontrol( 'String' , price , ...
                                                 'Parent' , SINGLE_PANEL , ...
                                                 'Style' , 'pushbutton'  , ...
                                                 'Callback' , callbr , ...
                                                 'HorizontalAlignment' , 'center' , ...
                                                 'Units' , 'pixels' , ...
                                                 'Visible' , 'on' , ...
                                                 'BackgroundColor' , med_blue  , ... 
                                                 'ForegroundColor' , white , ...
                                                 'FontUnits' , 'pixels' , ...
                                                 'FontSize' , 20 , ...
                                                 'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 2 + title_width_type + title_width_type/2 , text_length_secondary , title_width_type/2 ] ...                                        
                                               );
                                                      
                     
                  
                  
                  
            price = num2str( ticket_trip(1,12) , '%2.2f');
            price = [ '$' , price ];                  
            callbr = callname( function_name , char(input_button_name(1,12)) );                                           
            single_2_section_button = uicontrol( 'String' , price , ...
                                                 'Parent' , SINGLE_PANEL , ...
                                                 'Style' , 'pushbutton' , ...
                                                 'Callback' , callbr , ...
                                                 'HorizontalAlignment' , 'center' , ...
                                                 'Units' , 'pixels' , ...
                                                 'Visible' , 'on' , ...
                                                 'Interruptible' , 'on' , ...
                                                 'BackgroundColor' , med_blue  , ... 
                                                 'ForegroundColor' , white   , ...
                                                 'Callback' , callbr  , ...
                                                 'FontUnits' , 'pixels' , ...
                                                 'FontSize' , 20 , ...
                                                 'Position' , [ text_length_type + small_gap*1.3 , 1+title_width_type , text_length_regular , title_width_type/2 ] ...
                                                );
                                           
                                
                                                
                                                
            single_NA_tertiary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                             'Parent' , SINGLE_PANEL , ...
                                                             'Style' , 'text'  , ...
                                                             'HorizontalAlignment' , 'center' , ...
                                                             'Units' , 'pixels' , ...
                                                             'Visible' , 'on' , ...
                                                             'BackgroundColor' , med_blue  , ... 
                                                             'ForegroundColor' , white   , ...
                                                             'FontUnits' , 'pixels' , ...
                                                             'FontSize' , 15 , ...
                                                             'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 1+title_width_type , text_length_tertiary , title_width_type/2 ] ...
                                                            );
                                           
                                                           
                                              
            single_NA_secondary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                              'Parent' , SINGLE_PANEL , ...
                                                              'Style' , 'text'  , ...
                                                              'HorizontalAlignment' , 'center' , ...
                                                              'Units' , 'pixels' , ...
                                                              'Visible' , 'on' , ...
                                                              'BackgroundColor' , med_blue  , ... 
                                                              'ForegroundColor' , white   , ...
                                                              'FontUnits' , 'pixels' , ...
                                                              'FontSize' , 15 , ...
                                                              'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 1 + title_width_type , text_length_secondary , title_width_type/2 ] ...
                                                             );
                                                                  
                     
                  
                  
                  
                                                             
            price = num2str( ticket_trip(1,13) , '%2.2f');
            price = [ '$' , price ];                                                   
            callbr = callname( function_name , char(input_button_name(1,13)) );                                               
            single_interpeak_regular_button = uicontrol( 'String' , price , ...
                                                         'Parent' , SINGLE_PANEL , ...
                                                         'Style' , 'pushbutton' , ...
                                                         'Callback' , callbr , ...
                                                         'HorizontalAlignment' , 'center' , ...
                                                         'Units' , 'pixels' , ...
                                                         'Visible' , 'on' , ...
                                                         'Interruptible' , 'on' , ...
                                                         'BackgroundColor' , light_blue , ... 
                                                         'ForegroundColor' , black  , ...
                                                         'FontUnits' , 'pixels' , ...
                                                         'FontSize' , 20 , ...
                                                         'Position' , [ text_length_type + small_gap*1.3 , 2 + title_width_type/2 , text_length_regular , title_width_type/2 ] ...
                                                        );
                                                      
                                                        
                                                        
                                                           
            price = num2str( ticket_trip(1,14) , '%2.2f');
            price = [ '$' , price ];                                               
            callbr = callname( function_name , char(input_button_name(1,14)) );              
            single_interpeak_tertiary_button = uicontrol( 'String' , price , ...
                                                          'Parent' , SINGLE_PANEL , ...
                                                          'Style' , 'pushbutton'  , ...
                                                          'Callback' , callbr , ...
                                                          'HorizontalAlignment' , 'center' , ...
                                                          'Units' , 'pixels' , ...
                                                          'Visible' , 'on' , ...
                                                          'BackgroundColor' , light_blue , ... 
                                                          'ForegroundColor' , black   , ...
                                                          'FontUnits' , 'pixels' , ...
                                                          'FontSize' , 20 , ...
                                                          'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 2 + title_width_type/2  , text_length_tertiary , title_width_type/2 ] ...
                                                         );
                           
                      
                  
                  
                  
                  
                                                         
            price = num2str( ticket_trip(1,15) , '%2.2f');
            price = [ '$' , price ];                                
            callbr = callname( function_name , char(input_button_name(1,15)) );                 
            single_interpeak_secondary_button = uicontrol( 'String' , price , ...
                                                           'Parent' , SINGLE_PANEL , ...
                                                           'Style' , 'pushbutton'  , ...
                                                           'Callback' , callbr , ...
                                                           'HorizontalAlignment' , 'center' , ...
                                                           'Units' , 'pixels' , ...
                                                           'Visible' , 'on' , ...
                                                           'BackgroundColor' , light_blue , ... 
                                                           'ForegroundColor' , black   , ...
                                                           'FontUnits' , 'pixels' , ...
                                                           'FontSize' , 20 , ...
                                                           'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 2 + title_width_type/2 , text_length_secondary , title_width_type/2 ] ...                                        
                                                          );
            
                                                                                             
                                                                 
                                                          
                                                          
            price = num2str( ticket_trip(1,16) , '%2.2f');
            price = [ '$' , price ];
            callbr = callname( function_name , char(input_button_name(1,16)) );                                                     
            single_interpeak_2_section_button = uicontrol( 'String' , price , ...
                                                           'Parent' , SINGLE_PANEL , ...
                                                           'Style' , 'pushbutton' , ...
                                                           'Callback' , callbr , ...
                                                           'HorizontalAlignment' , 'center' , ...
                                                           'Units' , 'pixels' , ...
                                                           'Visible' , 'on' , ...
                                                           'Interruptible' , 'on' , ...
                                                           'BackgroundColor' , light_blue , ... 
                                                           'ForegroundColor' , black   , ...
                                                           'FontUnits' , 'pixels' , ...
                                                           'FontSize' , 20 , ...
                                                           'Position' , [ text_length_type + small_gap*1.3 , 1 , text_length_regular , title_width_type/2 ] ...
                                                          );
                                               
                                          
            single_interpeak_NA_tertiary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                                       'Parent' , SINGLE_PANEL , ...
                                                                       'Style' , 'text'  , ...
                                                                       'HorizontalAlignment' , 'center' , ...
                                                                       'Units' , 'pixels' , ...
                                                                       'Visible' , 'on' , ...
                                                                       'BackgroundColor' , light_blue , ... 
                                                                       'ForegroundColor' , black  , ...
                                                                       'FontUnits' , 'pixels' , ...
                                                                       'FontSize' , 15 , ...
                                                                       'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 1 , text_length_tertiary , title_width_type/2 ] ...
                                                                      );
                                          
                                                         
            single_interpeak_NA_secondary_2_section_button = uicontrol( 'String' , { '' , 'not available'} , ...
                                                                        'Parent' , SINGLE_PANEL , ...
                                                                        'Style' , 'text'  , ...
                                                                        'HorizontalAlignment' , 'center' , ...
                                                                        'Units' , 'pixels' , ...
                                                                        'Visible' , 'on' , ...
                                                                        'BackgroundColor' , light_blue , ... 
                                                                        'ForegroundColor' , black   , ...
                                                                        'FontUnits' , 'pixels' , ...
                                                                        'FontSize' , 15 , ...
                                                                        'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 1  , text_length_secondary , title_width_type/2 ] ...
                                                                       );
                                                                   
                
                  
                                                                       
            price = num2str( ticket_trip(1,17) , '%2.2f');
            price = [ '$' , price ];                                  
            callbr = callname( function_name , char(input_button_name(1,17)) );                                              
            daytrip_regular_button = uicontrol( 'String' , price , ...
                                                'Parent' , DAYTRIP_PANEL , ...
                                                'Style' , 'pushbutton' , ...
                                                'Callback' , callbr , ...
                                                'HorizontalAlignment' , 'center' , ...
                                                'Units' , 'pixels' , ...
                                                'Visible' , 'on' , ...
                                                'Interruptible' , 'on' , ...
                                                'BackgroundColor' , med_blue  , ... 
                                                'ForegroundColor' , white   , ...
                                                'FontUnits' , 'pixels' , ...
                                                'FontSize' , 20 , ...
                                                'Position' , [ text_length_type + small_gap*1.3 , 10 , text_length_regular , title_width_daytrip ] ...
                                               );
                             
                                               
                     
                   
                   
                   
                                               
            price = num2str( ticket_trip(1,18) , '%2.2f');
            price = [ '$' , price ];        
            callbr = callname( function_name , char(input_button_name(1,18)) );                                               
            daytrip_tertiary_button = uicontrol( 'String'  , price , ...
                                                 'Parent' , DAYTRIP_PANEL , ...
                                                 'Style' , 'pushbutton'  , ...
                                                 'Callback' , callbr , ...
                                                 'HorizontalAlignment' , 'center' , ...
                                                 'Units' , 'pixels' , ...
                                                 'Visible' , 'on' , ...
                                                 'BackgroundColor' , med_blue  , ... 
                                                 'ForegroundColor' , white , ...
                                                 'FontUnits' , 'pixels' , ...
                                                 'FontSize' , 20 , ...
                                                 'Position' , [ text_length_type + text_length_regular  + small_gap*2.3 , 10  , text_length_tertiary , title_width_daytrip ] ...
                                               );
                       
                                           
                                               
                                               
            price = num2str( ticket_trip(1,19) , '%2.2f');
            price = [ '$' , price ];                                   
            callbr = callname( function_name , char(input_button_name(1,19)) );                                    
            daytrip_secondary_button = uicontrol( 'String'   , price , ...
                                                  'Parent'   , DAYTRIP_PANEL , ...
                                                  'Style'    , 'pushbutton'  , ...
                                                  'Callback' , callbr , ...
                                                  'HorizontalAlignment' , 'center' , ...
                                                  'Units' , 'pixels' , ...
                                                  'Visible' , 'on' , ...
                                                  'BackgroundColor' , med_blue  , ... 
                                                  'ForegroundColor' , white  , ...
                                                  'FontUnits' , 'pixels' , ...
                                                  'FontSize' , 20 , ...
                                                  'Position' , [ text_length_type + text_length_regular  + text_length_tertiary + small_gap*3.3 , 10 , text_length_secondary , title_width_daytrip ] ...                                        
                                                );
                                            
                                                                   
            callbr = callname( function_name , char(input_button_name(1,20)) );                                               
            exit_ticket = uicontrol( 'String' , 'OK' ,  ...
                                     'Parent' , OK_PANEL , ...
                                     'Style' , 'pushbutton'  , ...
                                     'Callback' , callbr  , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'Visible' , 'on' , ...
                                     'ForegroundColor' , black   , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontSize' , 30 , ...
                                     'Position' , [ 1 , 1 , free_length , daytrip_width + single_width + multi_width + fare_width ] ...                                        
                                   );
                                            
                                                
                                             
                                                    
    % buttons
    % =========================== end =====================================
    % =====================================================================
                                                     
              
             
                         
    
    % static text
    %+++++++++++++++++++++++++++++ begin  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                     
                       
    
                                              
            text_fare = uicontrol( 'String' , 'FARE SCHEDULE' , ...
                                   'Parent' , FARE_PANEL , ...
                                   'Style' , 'text'  , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'on' , ...
                                   'BackgroundColor' , dark_blue  , ... 
                                   'ForegroundColor' , white  , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontWeight' , 'bold' , ...
                                   'FontSize' , 23 , ...
                                   'Position' , [ 15 , 18 , 200 , 25 ] ...
                                 );
                                           
                                 
                                                     
            text_regular = uicontrol( 'String' , 'Regular' , ...
                                      'Parent' , FARE_PANEL , ...
                                      'Style' , 'text'  , ...
                                      'HorizontalAlignment' , 'center' , ...
                                      'Units' , 'pixels' , ...
                                      'Visible' , 'on' , ...
                                      'BackgroundColor' , green  ,... 
                                      'ForegroundColor' , white  , ...
                                      'FontUnits' , 'pixels' , ...
                                      'FontWeight' , 'bold' , ...
                                      'FontSize' , 15 , ...
                                      'Position' , [ text_length_type + small_gap*1.3 + 40 , 18 , 90 , 20 ] ...                                        
                                   );
                                           
                                   
                                          
            text_tertiary = uicontrol( 'String' , {'Tertiary Students' , 'and Concession' , 'Holders' } , ...
                                       'Parent' , FARE_PANEL , ...
                                       'Style' , 'text'  , ...
                                       'HorizontalAlignment' , 'center' , ...
                                       'Units' , 'pixels' , ...
                                       'Visible' , 'on' , ...
                                       'BackgroundColor' , green , ... 
                                       'ForegroundColor' , white  , ...
                                       'FontUnits' , 'pixels' , ...
                                       'FontWeight' , 'bold' , ...
                                       'FontSize' , 15 , ...
                                       'Position' , [ text_length_type + text_length_regular  + small_gap*1.3 + 23 , 3 , 135, 55 ] ...                                        
                                    );
                                           
                                   
                                    
            text_secondary = uicontrol( 'String' , { 'Secondary and' , 'Primary' , 'Students' } , ...
                                        'Parent' , FARE_PANEL , ...
                                        'Style' , 'text'  , ...
                                        'HorizontalAlignment' , 'center' , ...
                                        'Units' , 'pixels' , ...
                                        'Visible' , 'on' , ...
                                        'BackgroundColor' , green , ... 
                                        'ForegroundColor' , white  , ...
                                        'FontUnits' , 'pixels' , ...
                                        'FontWeight' , 'bold' , ...
                                        'FontSize' , 15 , ...
                                        'Position' , [ text_length_type + text_length_regular  + text_length_tertiary  + small_gap*1.3 + 42 , 3 , 115, 55 ] ...                                        
                                     );
                                           
                                   
                                            
           text_multi = uicontrol( 'String' , 'MULTITRIP TICKET' , ...
                                   'Parent' , MULTI_PANEL , ...
                                   'Style' , 'text'  , ...
                                   'HorizontalAlignment' , 'center' , ...
                                   'Units' , 'pixels' , ...
                                   'Visible' , 'on' , ...
                                   'BackgroundColor' , white , ... 
                                   'ForegroundColor' , red  , ...
                                   'FontUnits' , 'pixels' , ...
                                   'FontWeight' , 'bold' , ...
                                   'FontSize' , 18 , ...
                                   'Position' , [ 2  , 5 + title_width_type*2 , 190 , 20 ] ...                                        
                                );
                                           
                                     
                                                     
           text_all_time_multi = uicontrol( 'String' , 'All Times' , ...
                                            'Parent' , MULTI_PANEL , ...
                                            'Style' , 'text'  , ...
                                            'HorizontalAlignment' , 'center' , ...
                                            'Units' , 'pixels' , ...
                                            'Visible' , 'on' , ...
                                            'BackgroundColor' , red , ... 
                                            'ForegroundColor' , white , ...
                                            'FontUnits' , 'pixels' , ...
                                            'FontWeight' , 'bold' , ...
                                            'FontSize' , 22 , ...
                                            'Position' , [ 6 , 2 + title_width_type + 37, 115 , 25] ...
                                          );
                             
                                          
                                                     
           text_Interpeak_multi = uicontrol( 'String' , 'Interpeak' , ...
                                             'Parent' , MULTI_PANEL , ...
                                             'Style' , 'text'  , ...
                                             'HorizontalAlignment' , 'center' , ...
                                             'Units' , 'pixels' , ...
                                             'Visible' , 'on' , ...
                                             'BackgroundColor' , grey, ... 
                                             'ForegroundColor' , black , ...
                                             'FontUnits' , 'pixels' , ...
                                             'FontWeight' , 'bold' , ...
                                             'FontSize' , 22 , ...
                                             'Position' , [ 6 , 39 , 115 , 25] ...
                                           );
                                           
                                           
                        
           text_zone_multi = uicontrol( 'String' , 'Zone' , ...
                                        'Parent' , MULTI_PANEL , ...
                                        'Style' , 'text'  , ...
                                        'HorizontalAlignment' , 'left' , ...
                                        'Units' , 'pixels' , ...
                                        'Visible' , 'on' , ...
                                        'BackgroundColor' , red , ... 
                                        'ForegroundColor' , white , ...
                                        'FontUnits' , 'pixels' , ...
                                        'FontWeight' , 'bold' , ...
                                        'FontSize' , 17 , ...
                                        'Position' , [ 150 ,  title_width_type + 65 , 75 , 20 ] ...
                                      );
                             
                                                    
                                                  
           text_2_section_multi = uicontrol( 'String' , '2 Section' , ...
                                             'Parent' , MULTI_PANEL , ...
                                             'Style' , 'text'  , ...
                                             'HorizontalAlignment' , 'left' , ...
                                             'Units' , 'pixels' , ...
                                             'Visible' , 'on' , ...
                                             'BackgroundColor' , red, ... 
                                             'ForegroundColor' , white , ...
                                             'FontUnits' , 'pixels' , ...
                                             'FontWeight' , 'bold' , ...
                                             'FontSize' , 17 , ...
                                             'Position' , [ 150 , title_width_type + 15 , 75 , 20 ] ...
                                            );
                             
                                          
                                                  
           text_zone__multi_interpeak = uicontrol( 'String' , 'Zone' , ...
                                                   'Parent' , MULTI_PANEL , ...
                                                   'Style' , 'text'  , ...
                                                   'HorizontalAlignment' , 'left' , ...
                                                   'Units' , 'pixels' , ...
                                                   'Visible' , 'on' , ...
                                                   'BackgroundColor' , grey , ... 
                                                   'ForegroundColor' , black , ...
                                                   'FontUnits' , 'pixels' , ...
                                                   'FontWeight' , 'bold' , ...
                                                   'FontSize' , 17 , ...
                                                   'Position' , [ 150 ,  65 , 75 , 20 ] ...
                                                 );
                             
                                                    
                                        
           text_2_section_multi_interpeak = uicontrol( 'String' , '2 Section' , ...
                                                       'Parent' , MULTI_PANEL , ...
                                                       'Style' , 'text'  , ...
                                                       'HorizontalAlignment' , 'left' , ...
                                                       'Units' , 'pixels' , ...
                                                       'Visible' , 'on' , ...
                                                       'BackgroundColor' , grey , ... 
                                                       'ForegroundColor' , black , ...
                                                       'FontUnits' , 'pixels' , ...
                                                       'FontWeight' , 'bold' , ...
                                                       'FontSize' , 17 , ...
                                                       'Position' , [ 150 , 15 , 75 , 20 ] ...
                                                     );
                                                        
                                   
                                         
           text_single = uicontrol( 'String' , 'SINGLETRIP TICKET' , ...
                                    'Parent' , SINGLE_PANEL , ...
                                    'Style' , 'text'  , ...
                                    'HorizontalAlignment' , 'center' , ...
                                    'Units' , 'pixels' , ...
                                    'Visible' , 'on' , ...
                                    'BackgroundColor' , white , ... 
                                    'ForegroundColor' , black , ...
                                    'FontUnits' , 'pixels' , ...
                                    'FontWeight' , 'bold' , ...
                                    'FontSize' , 18 , ...
                                    'Position' , [ 2  , 5 + title_width_type*2 , 200 , 20 ] ...                                        
                                  );
                                                                  
                                                     
                                                     
           text_all_time_single = uicontrol( 'String' , 'All Times' , ...
                                             'Parent' , SINGLE_PANEL , ...
                                             'Style' , 'text'  , ...
                                             'HorizontalAlignment' , 'center' , ...
                                             'Units' , 'pixels' , ...
                                             'Visible' , 'on' , ...
                                             'BackgroundColor' , med_blue , ... 
                                             'ForegroundColor' , white , ...
                                             'FontUnits' , 'pixels' , ...
                                             'FontWeight' , 'bold' , ...
                                             'FontSize' , 22 , ...
                                             'Position' , [ 6 , 2 + title_width_type + 37, 115 , 25] ...
                                            );
                                           
                                         
                                                     
           text_Interpeak_single = uicontrol( 'String' , 'Interpeak' , ...
                                              'Parent' , SINGLE_PANEL , ...
                                              'Style' , 'text'  , ...
                                              'HorizontalAlignment' , 'center' , ...
                                              'Units' , 'pixels' , ...
                                              'Visible' , 'on' , ...
                                              'BackgroundColor' , light_blue , ... 
                                              'ForegroundColor' , black , ...
                                              'FontUnits' , 'pixels' , ...
                                              'FontWeight' , 'bold' , ...
                                              'FontSize' , 22 , ...
                                              'Position' , [ 6 , 39 , 115 , 25] ...
                                             );
                                           
                                           
                                                  
           text_zone_single = uicontrol( 'String' , 'Zone' , ...
                                         'Parent' , SINGLE_PANEL , ...
                                         'Style' , 'text'  , ...
                                         'HorizontalAlignment' , 'left' , ...
                                         'Units' , 'pixels' , ...
                                         'Visible' , 'on' , ...
                                         'BackgroundColor' , med_blue , ... 
                                         'ForegroundColor' , white , ...
                                         'FontUnits' , 'pixels' , ...
                                         'FontWeight' , 'bold' , ...
                                         'FontSize' , 17 , ...
                                         'Position' , [ 150 ,  title_width_type + 65 , 75 , 20 ] ...
                                       );
                             
                                       
                                                  
           text_2_section_single = uicontrol( 'String' , '2 Section' , ...
                                              'Parent' , SINGLE_PANEL , ...
                                              'Style' , 'text'  , ...
                                              'HorizontalAlignment' , 'left' , ...
                                              'Units' , 'pixels' , ...
                                              'Visible' , 'on' , ...
                                              'BackgroundColor' , med_blue , ... 
                                              'ForegroundColor' , white , ...
                                              'FontUnits' , 'pixels' , ...
                                              'FontWeight' , 'bold' , ...
                                              'FontSize' , 17 , ...
                                              'Position' , [ 150 , title_width_type + 15 , 75 , 20 ] ...
                                             );
                             
                                                
                                                  
           text_zone_single_interpeak = uicontrol( 'String' , 'Zone' , ...
                                                   'Parent' , SINGLE_PANEL , ...
                                                   'Style' , 'text'  , ...
                                                   'HorizontalAlignment' , 'left' , ...
                                                   'Units' , 'pixels' , ...
                                                   'Visible' , 'on' , ...
                                                   'BackgroundColor' , light_blue , ... 
                                                   'ForegroundColor' , black , ...
                                                   'FontUnits' , 'pixels' , ...
                                                   'FontWeight' , 'bold' , ...
                                                   'FontSize' , 17 , ...
                                                   'Position' , [ 150 ,  65 , 75 , 20 ] ...
                                                 );
                             
                                                    
                                        
           text_2_section_single_interpeak = uicontrol( 'String' , '2 Section' , ...
                                                        'Parent' , SINGLE_PANEL , ...
                                                        'Style' , 'text'  , ...
                                                        'HorizontalAlignment' , 'left' , ...
                                                        'Units' , 'pixels' , ...
                                                        'Visible' , 'on' , ...
                                                        'BackgroundColor' , light_blue , ... 
                                                        'ForegroundColor' , black , ...
                                                        'FontUnits' , 'pixels' , ...
                                                        'FontWeight' , 'bold' , ...
                                                        'FontSize' , 17 , ...
                                                        'Position' , [ 150 , 15 , 75 , 20 ] ...
                                                      );
                                                        
                  
                      
           text_daytrip_title = uicontrol( 'String' , 'SINGLETRIP TICKET' , ...
                                           'Parent' , DAYTRIP_PANEL  , ...
                                           'Style' , 'text'  , ...
                                           'HorizontalAlignment' , 'center' , ...
                                           'Units' , 'pixels' , ...
                                           'Visible' , 'on' , ...
                                           'BackgroundColor' , white , ... 
                                           'ForegroundColor' , black , ...
                                           'FontUnits' , 'pixels' , ...
                                           'FontWeight' , 'bold' , ...
                                           'FontSize' , 18 , ...
                                           'Position' , [ 2  , 12 + title_width_daytrip , 200 , 20 ] ...                                        
                                          );
                                           
                                        
                                                     
           text_daytrip = uicontrol( 'String' , 'Daytrip' , ...
                                     'Parent' , DAYTRIP_PANEL , ...
                                     'Style' , 'text'  , ...
                                     'HorizontalAlignment' , 'center' , ...
                                     'Units' , 'pixels' , ...
                                     'Visible' , 'on' , ...
                                     'BackgroundColor' , med_blue , ... 
                                     'ForegroundColor' , white , ...
                                     'FontUnits' , 'pixels' , ...
                                     'FontWeight' , 'bold' , ...
                                     'FontSize' , 22 , ...
                                     'Position' , [ 6 , 20 , 90 , 25] ...
                                   );
                                           
                                        
    % static text
    %++++++++++++++++++++++++++++++  end  +++++++++++++++++++++++++++++++++
    %++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++      
    
              data_list  = [ multi_regular_button               , ... %1
                             multi_tertiary_button              , ... %2
                             multi_secondary_button             , ... %3
                             multi_2_section_button             , ... %4
                             multi_interpeak_regular_button     , ... %5
                             multi_interpeak_tertiary_button    , ... %6
                             multi_interpeak_secondary_button   , ... %7
                             multi_interpeak_2_section_button   , ... %8                                         
                             single_regular_button              , ... %9
                             single_tertiary_button             , ... %10
                             single_secondary_button            , ... %11
                             single_2_section_button            , ... %12
                             single_interpeak_regular_button    , ... %13
                             single_interpeak_tertiary_button   , ... %14
                             single_interpeak_secondary_button  , ... %15
                             single_interpeak_2_section_button  , ... %16
                             daytrip_regular_button             , ... %17
                             daytrip_tertiary_button            , ... %18
                             daytrip_secondary_button           , ... %19
                             exit_ticket                          ... %20
                           ];
    
              set( TICKET_FIGURE , 'UserData' , data_list );
              set( TICKET_FIGURE , 'Visible' , 'off' );
              
              set( data_list , 'Visible' , 'on' );
              set( data_list , 'Enable' , 'on' );
              set( TICKET_FIGURE , 'CloseRequestFcn' , 'closereq' );
              set( TICKET_FIGURE , 'Backingstore' , 'on' );
              
              watchoff( mouse_pointer );
    
output = TICKET_FIGURE;
